#!/usr/bin/env bash
# ports/ncurses/build.sh - the build=script body for the ncurses port (#745).
#
# WHY THIS IS A SCRIPT AND NOT build=objects. ncurses is not a fixed list of .c
# files: its library sources are GENERATED by ./configure and a tree of
# awk/sed/sh generators (curses.h from curses.h.in, term.h, comp_captab.c,
# names.c, fallback.c, init_keytry.h, expanded.c, lib_gen.c, ...). The honest
# way to track it is to let upstream's own build system produce them, so a
# version bump is a change to the sha256 pin and nothing else. mports still
# enforces the outcome: the header of ports/ncurses/PORT lists the lib and the
# symbols it must contain, and mports fails the build unless libncurses.a exists
# and every one of those symbols is DEFINED in it.
#
# CROSS-COMPILE MODEL. The MayteraOS "cross toolchain" is the host gcc with the
# freestanding userland flag set (ports.mk), not a separate triple, so we cannot
# lean on a sysroot. Two passes:
#   HOST pass  - a normal native ncurses build, used ONLY to produce `tic`, the
#                terminfo compiler that runs on the build host.
#   CROSS pass - configure with --host != --build so autoconf runs its generators
#                with BUILD_CC (host) but compiles the LIBRARY with our target
#                flags. Configure's function/type link-tests are made honest by
#                pointing LIBS at userland/libc's crt0.o + libc.a, so a probe for
#                (say) nl_langinfo correctly fails (absent) while one for poll
#                correctly succeeds (present). Two cache overrides are set for
#                things a cross build cannot probe by running: ssize_t IS defined
#                by our libc (ac_cv_type_ssize_t), and poll DOES work
#                (cf_cv_working_poll -> USE_FUNC_POLL, so ncurses uses poll, which
#                the kernel implements, instead of the select() stub).
#
# The build is NARROW (--disable-widec): userland has wchar.h but the emulator
# and this milestone are 8-bit/UTF-8-passthrough, and a narrow build avoids the
# wcwidth/wctob surface. Line drawing is still real: the maytera terminfo below
# uses smacs/rmacs/acsc and term_parse.c maps the DEC graphics set to Unicode.

set -euo pipefail

S="${MPORTS_SRC:?ncurses/build.sh: MPORTS_SRC unset}"     # unpacked+patched srcdir
OUT="${MPORTS_OUT:?ncurses/build.sh: MPORTS_OUT unset}"    # ports/out
CF="${MPORTS_CFLAGS:?ncurses/build.sh: MPORTS_CFLAGS unset}"  # full target compile profile
W="$(dirname "$S")"                       # ports/.work/ncurses (mports wants lib at $W/<lib>)
LIBC="$(cd "$OUT/../../libc" && pwd)"      # userland/libc
PORTDIR="$(cd "$OUT/../ncurses" && pwd)"   # userland/ports/ncurses (our non-tarball files)
BUILDTRIPLE="$(sh "$S/config.guess")"
NPROC="$(nproc 2>/dev/null || echo 2)"

echo "ncurses/build.sh: S=$S OUT=$OUT LIBC=$LIBC build-triple=$BUILDTRIPLE"

# --- HOST pass: build tic ---------------------------------------------------
HB="$W/host"; rm -rf "$HB"; mkdir -p "$HB"; cd "$HB"
"$S/configure" --without-shared --with-normal --without-cxx --without-cxx-binding \
  --without-ada --without-tests --without-manpages --disable-widec --without-develop \
  >host-conf.log 2>&1 || { echo "ncurses/build.sh: HOST configure FAILED"; tail -30 host-conf.log; exit 1; }
make -C include  >host-inc.log 2>&1 || { echo "ncurses/build.sh: HOST include gen FAILED"; tail -30 host-inc.log; exit 1; }
make -C ncurses  >host-lib.log 2>&1 || { echo "ncurses/build.sh: HOST libncurses FAILED"; tail -30 host-lib.log; exit 1; }
make -C progs tic >host-tic.log 2>&1 || { echo "ncurses/build.sh: HOST tic FAILED"; tail -30 host-tic.log; exit 1; }
TIC="$HB/progs/tic"
[ -x "$TIC" ] || { echo "ncurses/build.sh: host tic missing after build"; exit 1; }
echo "ncurses/build.sh: host tic OK ($("$TIC" -V))"

# --- CROSS pass: build the MayteraOS target libraries -----------------------
TB="$W/target"; rm -rf "$TB"; mkdir -p "$TB"; cd "$TB"
"$S/configure" \
  --host=x86_64-pc-none --build="$BUILDTRIPLE" \
  ac_cv_type_ssize_t=yes cf_cv_working_poll=yes \
  CC=gcc CFLAGS="$CF" CPPFLAGS="$CF" \
  LDFLAGS="-nostdlib -static" LIBS="$LIBC/crt0.o $LIBC/libc.a" \
  BUILD_CC=gcc BUILD_CFLAGS=-O2 AR=ar RANLIB=ranlib \
  --without-shared --with-normal --without-cxx --without-cxx-binding --without-ada \
  --without-progs --without-tests --without-tack --without-manpages --without-develop \
  --disable-widec --disable-termcap --disable-getcap --disable-home-terminfo \
  --disable-db-install --disable-stripping --enable-const \
  --with-default-terminfo-dir=/TERMINFO --with-terminfo-dirs=/TERMINFO \
  >cross-conf.log 2>&1 || { echo "ncurses/build.sh: CROSS configure FAILED"; tail -40 cross-conf.log; exit 1; }
make -j"$NPROC" libs >cross-make.log 2>&1 || { echo "ncurses/build.sh: CROSS make libs FAILED"; tail -40 cross-make.log; exit 1; }

[ -f "$TB/lib/libncurses.a" ] || { echo "ncurses/build.sh: CROSS build produced no libncurses.a"; exit 1; }

# Primary lib where mports expects it (it symbol-checks and installs $W/<lib>).
cp "$TB/lib/libncurses.a" "$W/libncurses.a"

# The generated public headers into the source tree's include/, so mports'
# headers= can install them by path.
cp "$TB/include/"*.h "$S/include/"

# The widget libraries are separate archives even in this single-tinfo build;
# mports only tracks the primary lib, so install these three ourselves.
mkdir -p "$OUT/lib" "$OUT/include"
for l in libpanel libmenu libform; do
  [ -f "$TB/lib/$l.a" ] || { echo "ncurses/build.sh: expected $l.a not built"; exit 1; }
  cp "$TB/lib/$l.a" "$OUT/lib/$l.a"
done
echo "ncurses/build.sh: libncurses.a + libpanel/libmenu/libform.a built"

# --- terminfo database ------------------------------------------------------
# Compiled with the tic we just built from THIS source, so the on-disk format
# matches the libncurses that reads it exactly. The honest, hand-written
# 'maytera' entry (matches term_parse.c) plus a minimal set of the standard
# entries from upstream's own misc/terminfo.src for apps that hardcode a name.
TIDIR="$OUT/terminfo"; rm -rf "$TIDIR"; mkdir -p "$TIDIR"
TERMINFO="$TIDIR" "$TIC" -x -o "$TIDIR" "$PORTDIR/terminfo/maytera.terminfo" \
  >"$W/tic-maytera.log" 2>&1 || { echo "ncurses/build.sh: tic FAILED on maytera.terminfo"; cat "$W/tic-maytera.log"; exit 1; }
TERMINFO="$TIDIR" "$TIC" -x -e ansi,vt100,vt100-am,linux,xterm,xterm-color,xterm-256color \
  -o "$TIDIR" "$S/misc/terminfo.src" \
  >"$W/tic-std.log" 2>&1 || { echo "ncurses/build.sh: tic FAILED on the standard subset"; cat "$W/tic-std.log"; exit 1; }

# Prove the entries the image depends on actually compiled (anti-no-op for the DB).
for want in m/maytera m/maytera-256color a/ansi v/vt100 l/linux x/xterm x/xterm-256color; do
  [ -f "$TIDIR/$want" ] || { echo "ncurses/build.sh: terminfo entry '$want' was not compiled"; exit 1; }
done
echo "ncurses/build.sh: terminfo db -> $TIDIR ($(find "$TIDIR" -type f | wc -l) entries: maytera + ansi/vt100/linux/xterm)"
