#!/bin/bash
# build-all.sh - Reproduce the MayteraOS NetSurf core-lib cross-compile (Phase 0/1).
# C only. Builds .o objects for libwapcaplet, libparserutils, libhubbub, libcss, libdom
# against the MayteraOS freestanding userland toolchain. Run on the build server.
set -e
ROOT=<workspace>
CC=$ROOT/cc.sh
PU=$ROOT/libparserutils/include
WC=$ROOT/libwapcaplet/include
HB=$ROOT/libhubbub/include
INC="-I$PU -I$WC -I$HB"

echo "### 1. generate sources (host tools: perl, python3, gperf, host cc) ###"
# libparserutils charset aliases
(cd $ROOT/libparserutils && perl build/make-aliases.pl)
# libhubbub html entities
(cd $ROOT/libhubbub && perl build/make-entities.pl)
# libhubbub element-type perfect hash
(cd $ROOT/libhubbub/src/treebuilder && gperf --output-file=autogenerated-element-type.c element-type.gperf)
# libcss select/computed/propstrings generators
(cd $ROOT/libcss && python3 src/select/select_generator.py)
# libcss per-property enum parsers
(cd $ROOT/libcss/src/parse/properties && \
   cc -O2 -o gen_parser css_property_parser_gen.c && \
   perl -pe'$_="" unless /^([^\#][^:]+):/;$_=$1." "' properties.gen > /tmp/props.txt && \
   for p in $(cat /tmp/props.txt); do \
     line=$(grep "^$p:" properties.gen); \
     [ -n "$line" ] && ./gen_parser -o autogenerated_$p.c "$line"; \
   done)

build_lib() { # $1=dir $2=extra-exclude-grep
  local d=$1 ex=$2
  mkdir -p $d/build/obj
  local ok=0 fail=0
  for f in $(find $d/src -name '*.c' | { [ -n "$ex" ] && grep -v "$ex" || cat; }); do
    local o=$d/build/obj/$(echo $f | tr / _).o
    if $CC -DWITHOUT_ICONV_FILTER -I$d/include -I$d/src $INC -c $f -o $o 2>/dev/null; then
      ok=$((ok+1)); else fail=$((fail+1)); echo "  FAIL $f"; fi
  done
  echo "$d: OK=$ok FAIL=$fail"
}

echo "### 2. cross-compile ###"
build_lib $ROOT/libwapcaplet
build_lib $ROOT/libparserutils   # filter.c now built (built-in codecs)
build_lib $ROOT/libhubbub
build_lib $ROOT/libcss
build_lib $ROOT/libdom

echo "### done. total .o: $(find $ROOT -name '*.o' -path '*build*' | wc -l) ###"

echo "### 3. create static archives (.a) ###"
cd $ROOT
for L in libwapcaplet libparserutils libhubbub libcss libdom; do
  rm -f $L.a
  ar rcs $L.a $(find $L/build/obj -name '*.o')
  echo "$L.a: $(ar t $L.a | wc -l) members"
done

echo "### 4. compile MayteraOS bindings + layout (MIT) ###"
NSI="-I$ROOT -I$ROOT/libdom/include -I$ROOT/libcss/include -I$ROOT/libhubbub/include -I$ROOT/libwapcaplet/include -I$ROOT/libparserutils/include -I$ROOT/shim-include"
$CC $NSI -c dom_hubbub_bind.c -o dom_hubbub_bind.o && echo '  dom_hubbub_bind.o OK'
$CC $NSI -c css_select_bind.c -o css_select_bind.o && echo '  css_select_bind.o OK'
$CC $NSI -c layout.c -o layout.o && echo '  layout.o OK'
echo "### done ###"
