#!/usr/bin/env bash
# snake/build.sh - see PORT for why build=script.
set -euo pipefail

PORT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
S="${MPORTS_SRC:?snake/build.sh: MPORTS_SRC unset}"
# srcdir=bsd-games-2.17/snake/snake has THREE path components, so the work
# root (ports/.work/snake) is three dirname() calls above $S, not two (see
# the hangman port's build.sh, whose two-component srcdir needs only two).
W="$(dirname "$(dirname "$(dirname "$S")")")"
WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

# pathnames.h: upstream ships only pathnames.h.in. Both paths are opened
# O_CREAT and failures are non-fatal (see PORT's SCOREFILE HONESTY note);
# pointed at /HOME, matching the moon-buggy port's SCORE_DIR precedent.
echo "snake/build.sh: writing pathnames.h"
cat > pathnames.h <<'EOF'
/* generated by userland/ports/snake/build.sh - no configure is run here. */
#define _PATH_RAWSCORES "/HOME/.snake.rawscores"
#define _PATH_LOGFILE   "/HOME/.snake.log"
EOF

CFLAGS="$MPORTS_CFLAGS -I$PORT_DIR/shim -DBSDGAME_PROGNAME=\"snake\" -w"

gcc $CFLAGS -c snake.c -o "$WORKDIR/sn_snake.o"
gcc $CFLAGS -c "$PORT_DIR/bsdgame_compat.c" -o "$WORKDIR/sn_compat.o"

rm -f "$W/libsnake.a"
ar rcs "$W/libsnake.a" "$WORKDIR"/sn_*.o
echo "snake/build.sh: OK -> $W/libsnake.a"
