/* GENERATED by tools/lua-oracle/gen_expect.py - DO NOT HAND-EDIT.
 *
 * Ground truth for userland/apps/luacheck. Every expected string below was
 * produced by TWO independent host Lua builds that had to agree first:
 *   A: Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio
 *      (Debian bookworm /usr/bin/lua5.4 - different patch release, different
 *       toolchain, glibc, LUA_USE_LINUX build configuration)
 *   B: Lua 5.4.8  Copyright (C) 1994-2025 Lua.org, PUC-Rio
 *      (a native host build of the SAME sha256-pinned upstream tarball this
 *       port fetches, built with upstream's own `make linux` against glibc)
 * The generator refuses to emit any case the two disagree about, and runs
 * each oracle twice to catch a non-deterministic case. No expectation here
 * is hand-written and none of it came from our own build, so a PASS is
 * agreement with external ground truth, not self-consistency.
 *
 * 21 cases.
 */
#ifndef LUACHECK_EXPECT_H
#define LUACHECK_EXPECT_H

typedef struct {
    const char *name;
    const char *src;
    const char *want;
} lua_case_t;

static const lua_case_t EXPECT_CASES[] = {
  { "arith",
    /* src */
    "\nlocal o = {}\no[#o+1] = tostring(7 // 2)\no[#o+1] = tostring(7 / 2)\no[#o+1] = tostring(7 % 3)\no[#o+1] = tostring(-7 // 2)\no[#o+1] = tostring(-7 % 3)\no[#o+1] = tostring(2^10)\no[#o+1] = math.type(1) .. \",\" .. math.type(1.0) .. \",\" .. tostring(math.type(\"x\"))\no[#o+1] = tostring(math.maxinteger) .. \",\" .. tostring(math.mininteger)\no[#o+1] = tostring(math.maxinteger + 1 == math.mininteg"
    "er)\no[#o+1] = string.format(\"%d %d\", 3 // 1, math.tointeger(4.0))\no[#o+1] = tostring(1 == 1.0) .. \",\" .. tostring(math.type(1 + 1.0))\no[#o+1] = tostring(5 // 0.0) .. \",\" .. tostring(0/0 ~= 0/0)\nreturn table.concat(o, \"\\n\")\n"
    ,
    /* want */
    "3\n3.5\n1\n-4\n2\n1024.0\ninteger,float,nil\n9223372036854775807,-9223372036854775808\ntrue\n3 4\ntrue,float\ninf,true"
  },
  { "bitops",
    /* src */
    "\nlocal o = {}\no[#o+1] = tostring(0xF0 | 0x0F)\no[#o+1] = tostring(0xFF & 0x0F)\no[#o+1] = tostring(0xFF ~ 0x0F)\no[#o+1] = tostring(~0)\no[#o+1] = tostring(1 << 40)\no[#o+1] = tostring(-1 >> 60)\no[#o+1] = tostring(1 << 64) .. \",\" .. tostring(1 >> 64)\nreturn table.concat(o, \"\\n\")\n"
    ,
    /* want */
    "255\n15\n240\n-1\n1099511627776\n15\n0,0"
  },
  { "floatfmt",
    /* src */
    "\n-- %.17g is NOT here: see the KNOWN-GAP section of\n-- userland/apps/luacheck/main.c. This libc's float formatter cannot emit\n-- more than about 16 correct significant digits, and that gap is pinned\n-- there with its cause rather than left to redden this corpus forever.\nlocal o = {}\no[#o+1] = tostring(1/3)\no[#o+1] = tostring(0.1 + 0.2)\no[#o+1] = tostring(1.0)\no[#o+1] = tostring(1e300 * 1e1"
    "0)\no[#o+1] = string.format(\"%5.2f|%e|%g\", 3.14159, 12345.6789, 0.000012345)\no[#o+1] = string.format(\"%10.4f|%-8d|%+d|%05d\", 2.5, 42, 7, 33)\no[#o+1] = string.format(\"%x %X %o %c\", 48879, 48879, 8, 65)\nreturn table.concat(o, \"\\n\")\n"
    ,
    /* want */
    "0.33333333333333\n0.3\n1.0\ninf\n 3.14|1.234568e+04|1.2345e-05\n    2.5000|42      |+7|00033\nbeef BEEF 10 A"
  },
  { "strings",
    /* src */
    "\nlocal o = {}\no[#o+1] = (\"hello\"):upper() .. (\"WORLD\"):lower()\no[#o+1] = string.rep(\"ab\", 3, \"-\")\no[#o+1] = string.sub(\"abcdefgh\", 2, -3)\no[#o+1] = string.reverse(\"abcdef\")\no[#o+1] = table.concat({string.byte(\"AZ\", 1, 2)}, \",\")\no[#o+1] = string.char(77, 97, 121, 116, 101, 114, 97)\no[#o+1] = tostring(#((\"x\"):rep(1000)))\no[#o+1] = string.format(\"%q\", \"a\\nb\\\"c\\\\d\\te"
    "\")\no[#o+1] = (\"  padded  \"):gsub(\"^%s*(.-)%s*$\", \"[%1]\")\nreturn table.concat(o, \"\\n\")\n"
    ,
    /* want */
    "HELLOworld\nab-ab-ab\nbcdef\nfedcba\n65,90\nMaytera\n1000\n\"a\\\nb\\\"c\\\\d\\9e\"\n[padded]"
  },
  { "patterns",
    /* src */
    "\nlocal o = {}\nlocal y, m, d = (\"2026-08-13\"):match(\"(%d+)-(%d+)-(%d+)\")\no[#o+1] = y .. \"/\" .. m .. \"/\" .. d\no[#o+1] = ((\"the quick brown fox\"):gsub(\"%w+\", function(w) return w:upper() end))\no[#o+1] = tostring(select(2, (\"aaa\"):gsub(\"a\", \"b\")))\nlocal t = {}\nfor w in (\"a,bb,ccc,dddd\"):gmatch(\"[^,]+\") do t[#t+1] = \"[\" .. w .. \"]\" end\no[#o+1] = table.concat(t)\no[#o+1]"
    " = table.concat({(\"hello.world\"):find(\".\", 1, true)}, \",\")\no[#o+1] = ((\"x=1, y=22\"):gsub(\"(%w+)=(%w+)\", \"%2=%1\"))\no[#o+1] = ((\"abc\"):gsub(\"%a\", {a = \"1\", b = \"2\"}))\no[#o+1] = tostring((\"Hello World\"):match(\"^%u%l+\"))\no[#o+1] = ((\"a.b.c\"):gsub(\"%.\", \"/\"))\nreturn table.concat(o, \"\\n\")\n"
    ,
    /* want */
    "2026/08/13\nTHE QUICK BROWN FOX\n3\n[a][bb][ccc][dddd]\n6,6\n1=x, 22=y\n12c\nHello\na/b/c"
  },
  { "tables",
    /* src */
    "\nlocal t = {5, 3, 9, 1, 7}\nlocal o = {}\ntable.sort(t)\no[#o+1] = table.concat(t, \",\")\ntable.sort(t, function(a, b) return a > b end)\no[#o+1] = table.concat(t, \",\")\ntable.insert(t, 3, 100)\no[#o+1] = table.concat(t, \",\")\ntable.remove(t, 1)\no[#o+1] = table.concat(t, \",\")\no[#o+1] = tostring(#t)\no[#o+1] = table.concat({table.unpack({1, 2, 3})}, \"|\")\nlocal p = table.pack(10, 20, 30)"
    "\no[#o+1] = table.concat(p, \"+\") .. \":\" .. tostring(p.n)\nlocal big = {}\nfor i = 1, 200 do big[i] = (i * 37) % 101 end\ntable.sort(big)\no[#o+1] = table.concat(big, \",\", 1, 12) .. \"/\" .. tostring(#big)\no[#o+1] = table.concat(table.move({1,2,3,4,5}, 2, 4, 1, {}), \",\")\nreturn table.concat(o, \"\\n\")\n"
    ,
    /* want */
    "1,3,5,7,9\n9,7,5,3,1\n9,7,100,5,3,1\n7,100,5,3,1\n5\n1|2|3\n10+20+30:3\n0,1,1,2,2,3,3,4,4,5,5,6/200\n2,3,4"
  },
  { "meta",
    /* src */
    "\nlocal V = {}\nV.__index = V\nfunction V.new(x, y) return setmetatable({x = x, y = y}, V) end\nV.__add = function(a, b) return V.new(a.x + b.x, a.y + b.y) end\nV.__tostring = function(v) return \"(\" .. v.x .. \",\" .. v.y .. \")\" end\nV.__eq = function(a, b) return a.x == b.x and a.y == b.y end\nV.__len = function() return 2 end\nV.__call = function(self, k) return self[k] end\nV.__concat = func"
    "tion(a, b) return tostring(a) .. tostring(b) end\nlocal a, b = V.new(1, 2), V.new(3, 4)\nlocal o = {}\no[#o+1] = tostring(a + b)\no[#o+1] = tostring(a == V.new(1, 2))\no[#o+1] = tostring(#a)\no[#o+1] = tostring(a(\"x\"))\no[#o+1] = a .. b\nlocal prox = setmetatable({}, {__index = function(_, k) return \"gen:\" .. k end})\no[#o+1] = prox.foo\no[#o+1] = tostring(getmetatable(\"s\") ~= nil)\nreturn ta"
    "ble.concat(o, \"\\n\")\n"
    ,
    /* want */
    "(4,6)\ntrue\n2\n1\n(1,2)(3,4)\ngen:foo\ntrue"
  },
  { "closures",
    /* src */
    "\nlocal function counter() local n = 0 return function() n = n + 1 return n end end\nlocal c1, c2 = counter(), counter()\nlocal o = {}\no[#o+1] = table.concat({c1(), c1(), c1(), c2()}, \",\")\nlocal fns = {}\nfor i = 1, 3 do fns[i] = function() return i * i end end\no[#o+1] = table.concat({fns[1](), fns[2](), fns[3]()}, \",\")\nlocal function fib(n) if n < 2 then return n end return fib(n-1) + fib("
    "n-2) end\no[#o+1] = tostring(fib(20))\nlocal acc = 0\nlocal function tailsum(n, a) if n == 0 then return a end return tailsum(n - 1, a + n) end\nacc = tailsum(10000, 0)\no[#o+1] = tostring(acc)\nreturn table.concat(o, \"\\n\")\n"
    ,
    /* want */
    "1,2,3,1\n1,4,9\n6765\n50005000"
  },
  { "coroutines",
    /* src */
    "\nlocal function j(...)\n  local t = table.pack(...)\n  for i = 1, t.n do t[i] = tostring(t[i]) end\n  return table.concat(t, \",\")\nend\n\nlocal co = coroutine.create(function(a, b)\n  local c = coroutine.yield(a + b)\n  local d = coroutine.yield(c * 2)\n  return a + b + c + d\nend)\nlocal o = {}\no[#o+1] = j(coroutine.resume(co, 1, 2))\no[#o+1] = j(coroutine.resume(co, 10))\no[#o+1] = j(coroutin"
    "e.resume(co, 100))\no[#o+1] = coroutine.status(co)\no[#o+1] = j(coroutine.resume(co))\nlocal g = coroutine.wrap(function() for i = 1, 3 do coroutine.yield(i) end end)\no[#o+1] = table.concat({g(), g(), g()}, \",\")\no[#o+1] = j(coroutine.isyieldable())\nlocal bad = coroutine.create(function() error(\"inside\") end)\no[#o+1] = j(coroutine.resume(bad))\nreturn table.concat(o, \"\\n\")\n"
    ,
    /* want */
    "true,3\ntrue,20\ntrue,113\ndead\nfalse,cannot resume dead coroutine\n1,2,3\nfalse\nfalse,case:22: inside"
  },
  { "errors",
    /* src */
    "\nlocal function j(...)\n  local t = table.pack(...)\n  for i = 1, t.n do t[i] = tostring(t[i]) end\n  return table.concat(t, \",\")\nend\n\nlocal o = {}\no[#o+1] = j(pcall(function() error(\"boom\") end))\no[#o+1] = j(pcall(function() error(\"nopos\", 0) end))\nlocal ok2, err2 = pcall(function() error({code = 42}) end)\no[#o+1] = j(ok2, err2.code)\no[#o+1] = j(pcall(function() return nil + 1 end))"
    "\no[#o+1] = j(pcall(function() local t = nil return t.x end))\no[#o+1] = j(xpcall(function() error(\"deep\") end, function(m) return \"handled:\" .. m end))\no[#o+1] = j(pcall(function() return (\"x\"):rep(3) end))\no[#o+1] = j(select(1, pcall(error)))\nreturn table.concat(o, \"\\n\")\n"
    ,
    /* want */
    "false,case:9: boom\nfalse,nopos\nfalse,42\nfalse,case:13: attempt to perform arithmetic on a nil value\nfalse,case:14: attempt to index a nil value (local 't')\nfalse,handled:case:15: deep\ntrue,xxx\nfalse,nil"
  },
  { "os_date",
    /* src */
    "\nlocal o = {}\no[#o+1] = os.date(\"!%Y-%m-%d %H:%M:%S\", 0)\no[#o+1] = os.date(\"!%Y-%m-%dT%H:%M:%S\", 1234567890)\no[#o+1] = os.date(\"!%j|%w|%p|%y|%m\", 1234567890)\no[#o+1] = os.date(\"!%A %B\", 1234567890)\nlocal t = os.date(\"!*t\", 1234567890)\no[#o+1] = table.concat({t.year, t.month, t.day, t.hour, t.min, t.sec, t.wday, t.yday}, \",\")\no[#o+1] = tostring(os.difftime(100, 40))\no[#o+1] = os"
    ".date(\"!%Y-%m-%d\", 2147483647)\nreturn table.concat(o, \"\\n\")\n"
    ,
    /* want */
    "1970-01-01 00:00:00\n2009-02-13T23:31:30\n044|5|PM|09|02\nFriday February\n2009,2,13,23,31,30,6,44\n60.0\n2038-01-19"
  },
  { "utf8",
    /* src */
    "\nlocal o = {}\nlocal s = utf8.char(72, 228, 8364, 128169)\no[#o+1] = tostring(#s)\no[#o+1] = tostring(utf8.len(s))\nlocal cps = {}\nfor _, c in utf8.codes(s) do cps[#cps+1] = c end\no[#o+1] = table.concat(cps, \",\")\no[#o+1] = table.concat({utf8.codepoint(s, 1, #s)}, \",\")\no[#o+1] = tostring(utf8.offset(s, 3))\no[#o+1] = table.concat({string.byte(s, 1, #s)}, \",\")\nreturn table.concat(o, \"\\n"
    "\")\n"
    ,
    /* want */
    "10\n4\n72,228,8364,128169\n72,228,8364,128169\n4\n72,195,164,226,130,172,240,159,146,169"
  },
  { "pack",
    /* src */
    "\nlocal o = {}\nlocal b = string.pack(\"<i4i2\", 305419896, -2)\no[#o+1] = tostring(#b)\no[#o+1] = table.concat({string.byte(b, 1, #b)}, \",\")\no[#o+1] = table.concat({string.unpack(\"<i4i2\", b)}, \",\")\no[#o+1] = tostring(string.packsize(\"<i4i2d\"))\no[#o+1] = table.concat({string.byte(string.pack(\">I8\", 1), 1, 8)}, \",\")\no[#o+1] = table.concat({string.byte(string.pack(\"<d\", 1.5), 1, 8)}"
    ", \",\")\no[#o+1] = tostring((string.unpack(\"<d\", string.pack(\"<d\", 3.25))))\no[#o+1] = table.concat({string.byte(string.pack(\"z\", \"hi\"), 1, 3)}, \",\")\nreturn table.concat(o, \"\\n\")\n"
    ,
    /* want */
    "6\n120,86,52,18,254,255\n305419896,-2,7\n14\n0,0,0,0,0,0,0,1\n0,0,0,0,0,0,248,63\n3.25\n104,105,0"
  },
  { "load_and_dump",
    /* src */
    "\nlocal function j(...)\n  local t = table.pack(...)\n  for i = 1, t.n do t[i] = tostring(t[i]) end\n  return table.concat(t, \",\")\nend\n\nlocal o = {}\nlocal f = load(\"local a,b = ... return a*b\", \"=inner\")\no[#o+1] = tostring(f(6, 7))\no[#o+1] = j(load(\"this is not lua\", \"=bad\"))\nlocal i = 0\n::top:: i = i + 1 if i < 5 then goto top end\no[#o+1] = tostring(i)\nlocal dumped = string.dum"
    "p(f)\no[#o+1] = tostring(#dumped > 0) .. \",\" .. tostring(dumped:byte(1))\no[#o+1] = tostring(load(dumped)(3, 4))\no[#o+1] = j(load(dumped, \"=chunk\", \"t\"))\nreturn table.concat(o, \"\\n\")\n"
    ,
    /* want */
    "42\nnil,bad:1: syntax error near 'is'\n5\ntrue,27\n12\nnil,attempt to load a binary chunk (mode is 't')"
  },
  { "mathlib",
    /* src */
    "\nlocal o = {}\no[#o+1] = string.format(\"%.10f\", math.sqrt(2))\no[#o+1] = string.format(\"%.10f\", math.exp(1))\no[#o+1] = string.format(\"%.10f\", math.log(100, 10))\no[#o+1] = string.format(\"%.10f\", math.log(8, 2))\no[#o+1] = string.format(\"%.10f\", math.sin(1) + math.cos(1))\no[#o+1] = table.concat({math.floor(-3.5), math.ceil(-3.5), math.abs(-9), math.fmod(7, 3)}, \",\")\no[#o+1] = table.c"
    "oncat({math.max(3, 9, 2), math.min(3, 9, 2)}, \",\")\no[#o+1] = tostring(math.tointeger(2^53)) .. \",\" .. tostring(math.tointeger(1.5))\no[#o+1] = string.format(\"%.6f\", math.pi)\no[#o+1] = string.format(\"%.10f\", math.ult(1, 2) and 1.0 or 0.0)\nreturn table.concat(o, \"\\n\")\n"
    ,
    /* want */
    "1.4142135624\n2.7182818285\n2.0000000000\n3.0000000000\n1.3817732907\n-4,-3,9,1\n9,2\n9007199254740992,nil\n3.141593\n1.0000000000"
  },
  { "tonumber",
    /* src */
    "\nlocal o = {}\no[#o+1] = tostring(tonumber(\"42\"))\no[#o+1] = tostring(tonumber(\"0x1F\"))\no[#o+1] = tostring(tonumber(\"ff\", 16))\no[#o+1] = tostring(tonumber(\"  3.5e2  \"))\no[#o+1] = tostring(tonumber(\"nope\"))\no[#o+1] = tostring(tonumber(\"z\", 36))\no[#o+1] = tostring(math.type(tonumber(\"3\"))) .. \",\" .. tostring(math.type(tonumber(\"3.0\")))\no[#o+1] = tostring(0x10) .. \",\" .. tos"
    "tring(1e2) .. \",\" .. tostring(.5)\no[#o+1] = tostring(tonumber(\"10\", 2)) .. \",\" .. tostring(tonumber(\"-17\"))\nreturn table.concat(o, \"\\n\")\n"
    ,
    /* want */
    "42\n31\n255\n350.0\nnil\n35\ninteger,float\n16,100.0,0.5\n2,-17"
  },
  { "hexfloat",
    /* src */
    "\nlocal o = {}\no[#o+1] = tostring(tonumber(\"0x1p4\"))\no[#o+1] = tostring(0x1p4)\no[#o+1] = tostring(tonumber(\"0xA.8p0\"))\no[#o+1] = tostring(0x.8p1)\nreturn table.concat(o, \"\\n\")\n"
    ,
    /* want */
    "16.0\n16.0\n10.5\n1.0"
  },
  { "strorder",
    /* src */
    "\nlocal t = {\"banana\", \"Apple\", \"cherry\", \"apple\", \"Banana\", \"APPLE\", \"app\"}\ntable.sort(t)\nlocal o = {table.concat(t, \",\")}\no[#o+1] = table.concat({tostring(\"a\" < \"b\"), tostring(\"A\" < \"a\"), tostring(\"abc\" < \"abd\"),\n                        tostring(\"abc\" < \"abcd\"), tostring(\"\" < \"a\")}, \",\")\no[#o+1] = tostring((\"z\"):rep(3) > (\"z\"):rep(2))\no[#o+1] = tost"
    "ring(\"\\1\\2\" < \"\\1\\3\")\nreturn table.concat(o, \"\\n\")\n"
    ,
    /* want */
    "APPLE,Apple,Banana,app,apple,banana,cherry\ntrue,true,true,true,true\ntrue\ntrue"
  },
  { "rawops",
    /* src */
    "\nlocal mt = {\n  __index = function() return \"meta\" end,\n  __newindex = function(t, k, v) rawset(t, k, \"blocked:\" .. tostring(v)) end,\n  __len = function() return 99 end,\n}\nlocal t = setmetatable({1, 2, 3}, mt)\nlocal o = {}\no[#o+1] = tostring(t.missing) .. \",\" .. tostring(rawget(t, \"missing\"))\nt.x = \"value\"\no[#o+1] = tostring(rawget(t, \"x\"))\no[#o+1] = tostring(#t) .. \",\" .. "
    "tostring(rawlen(t))\no[#o+1] = tostring(rawequal(t, t)) .. \",\" .. tostring(rawequal({}, {}))\no[#o+1] = type(t) .. \",\" .. type(nil) .. \",\" .. type(print) .. \",\" .. type(2) .. \",\" .. type(\"s\")\nreturn table.concat(o, \"\\n\")\n"
    ,
    /* want */
    "meta,nil\nblocked:value\n99,3\ntrue,false\ntable,nil,function,number,string"
  },
  { "gc",
    /* src */
    "\nlocal o = {}\ncollectgarbage(\"collect\")\nlocal before = collectgarbage(\"count\")\nlocal junk = {}\nfor i = 1, 20000 do junk[i] = (\"x\"):rep(24) end\nlocal during = collectgarbage(\"count\")\njunk = nil\ncollectgarbage(\"collect\")\nlocal after = collectgarbage(\"count\")\no[#o+1] = tostring(during > before)\no[#o+1] = tostring(after < during)\no[#o+1] = tostring(collectgarbage(\"count\") > 0)"
    "\nlocal seen = false\ndo\n  local fin = setmetatable({}, {__gc = function() seen = true end})\n  fin = nil\nend\ncollectgarbage(\"collect\")\no[#o+1] = tostring(seen)\no[#o+1] = tostring(collectgarbage(\"isrunning\"))\nreturn table.concat(o, \"\\n\")\n"
    ,
    /* want */
    "true\ntrue\ntrue\ntrue\ntrue"
  },
  { "iteration",
    /* src */
    "\nlocal o = {}\nlocal s = 0\nfor i, v in ipairs({10, 20, 30, 40, 50}) do s = s + i * v end\no[#o+1] = tostring(s)\nlocal keys = {}\nfor k in pairs({a = 1, b = 2, c = 3, d = 4}) do keys[#keys+1] = k end\ntable.sort(keys)\no[#o+1] = table.concat(keys, \",\")\no[#o+1] = tostring(next({}) == nil)\no[#o+1] = tostring(#({1, 2, 3}))\nlocal acc = {}\nfor i = 10, 1, -3 do acc[#acc+1] = i end\no[#o+1] = tabl"
    "e.concat(acc, \",\")\nlocal n = 0\nfor _ in (\"a b c d\"):gmatch(\"%a\") do n = n + 1 end\no[#o+1] = tostring(n)\nreturn table.concat(o, \"\\n\")\n"
    ,
    /* want */
    "550\na,b,c,d\ntrue\n3\n10,7,4,1\n4"
  },
};

#define EXPECT_NCASES ((int)(sizeof(EXPECT_CASES)/sizeof(EXPECT_CASES[0])))

#endif /* LUACHECK_EXPECT_H */
