// SPDX-License-Identifier: MIT
// Copyright (c) MayteraOS contributors.
// Full license text: userland/libc/LICENSE (MIT License).
//
// ctinvoke.c - contract_invoke(): reaching ANOTHER app's contract (#235).
//
// contract.c is how an app ANSWERS a contract call. This file is how a caller
// ASKS one. It was lifted verbatim out of userland/apps/ctl/main.c when a
// SECOND caller appeared: libc/aiclient.c's settings.get / settings.set tools,
// which until #235 carried their own hardcoded if-else chain over a different
// key set from the real one. Two copies of "how do I reach an app's contract"
// is the exact fault the contract API exists to remove, so there is one, here,
// and ctl now calls it too.
//
// WHY A SPAWN AND NOT SOMETHING CLEVERER (docs/CONTRACT_API.md section 3):
//   - no new syscall: SYS_SPAWN_ARGS (198) and SYS_SPAWN_REDIR (247) already
//     give argv and stdout capture, so nothing new crosses the kernel boundary;
//   - it works whether or not a GUI instance of the target app is running,
//     which a message-passing design would not: the message would have nobody
//     to answer it, and Settings is closed almost always;
//   - it cannot drift from the app, because it IS the app answering.
//
// The app's output also lands on the serial console through the kernel's fd-1
// fallback (kernel/proc/fdlayer.c:1468), so a harness with no GUI still sees
// every result even when the capture file cannot be created.

#include "contract.h"
#include "string.h"
#include "stdio.h"
#include "unistd.h"
#include "stdlib.h"   // open() is declared here, not in fcntl.h
#include "fcntl.h"
#include "syscall.h"
#include "userconf.h"

// #235: /AITOOLS/CONTRACTS.YML, NOT /AITOOLS/INDEX.YML. #233 named this
// INDEX.YML, which is ALREADY TAKEN: /AITOOLS/INDEX.YML on the golden is the AI
// TOOL index (lines of "  - id: calc.eval, summary: ..."), loaded by
// aiclient.c. Two different generated files under one name is the phantom this
// whole area of the tree keeps producing; measured on golden 2016, `ctl apps`
// printed the AI tool list. The lookup below happened to fail SAFE on that
// content (no line carries both "app: " and "path: ", so it fell through to the
// /APPS/<UPPERCASE> convention), which is exactly why it would have gone
// unnoticed until someone trusted the output.
#define CT_INDEX        "/AITOOLS/CONTRACTS.YML"
#define CT_TMP_FALLBACK "/TMP/CTL.OUT"

// ---------------------------------------------------------------------------
// app -> binary path.
//
// /AITOOLS/INDEX.YML is GENERATED by tools/contract-lint/contract-lint.py from
// the source tree, so it is derived and gated, never hand-maintained. When it
// is absent (a hand-deployed test image) we fall back to the launch-name
// convention the build's install step already resolves by: /APPS/<UPPERCASE>.
// Deriving the fallback from the convention rather than from a second table is
// deliberate - a hardcoded name map is exactly the phantom that shipped
// /APPS/COMPOSITOR while the kernel launched /APPS/COMPOSIT.
// ---------------------------------------------------------------------------
static int index_lookup(const char *app, char *out, int ocap) {
    int fd = open(CT_INDEX, O_RDONLY);
    if (fd < 0) return 0;
    static char buf[8192];
    long n = read(fd, buf, sizeof(buf) - 1);
    close(fd);
    if (n <= 0) return 0;
    buf[n] = 0;
    // Lines: "  - {app: settings, path: /APPS/SETTINGS, title: Settings, ...}"
    for (long i = 0; i < n; ) {
        long e = i; while (e < n && buf[e] != '\n') e++;
        buf[e] = 0;
        const char *a = strstr(buf + i, "app: ");
        const char *p = strstr(buf + i, "path: ");
        if (a && p) {
            a += 5;
            int L = 0; while (a[L] && a[L] != ',' && a[L] != '}' && a[L] != ' ') L++;
            if ((int)strlen(app) == L && !strncmp(a, app, (size_t)L)) {
                p += 6;
                int q = 0;
                while (p[q] && p[q] != ',' && p[q] != '}' && p[q] != ' ' && q < ocap - 1) {
                    out[q] = p[q]; q++;
                }
                out[q] = 0;
                return q > 0;
            }
        }
        i = e + 1;
    }
    return 0;
}

void contract_app_path(const char *app, char *out, int ocap) {
    if (ocap <= 0) return;
    if (index_lookup(app, out, ocap)) return;
    int j = 0;
    const char *pfx = "/APPS/";
    while (*pfx && j < ocap - 1) out[j++] = *pfx++;
    for (int i = 0; app[i] && j < ocap - 1; i++) {
        char c = app[i];
        out[j++] = (c >= 'a' && c <= 'z') ? (char)(c - 'a' + 'A') : c;
    }
    out[j] = 0;
}

// ---------------------------------------------------------------------------
// WHERE THE CAPTURE FILE GOES, and why this is not a constant.
//
// sys_spawn_redir() fails AS A WHOLE when it cannot create its output file, and
// reports the same failure as a missing binary. Two live runs of ctl were lost
// to that: /CONFIG is effectively root-only for a uid-1000 session (the caveat
// in libc/userconf.c:8-12) and /TMP exists on the image but is owned by root,
// so a uid-1000 session can create a file in neither. Both times the client
// reported "cannot spawn /APPS/SETTINGS" for an app that was installed and
// answering contract calls perfectly when run directly.
//
// So the capture goes in the CALLER'S OWN HOME, resolved at runtime by the same
// libc helper every per-user config path uses, with a fallback chain rather
// than one hardcoded path, and a last resort that runs with no capture at all.
// ---------------------------------------------------------------------------
int contract_invoke(const char *app, int argc, char **argv, char *out, int ocap) {
    if (ocap > 0) out[0] = 0;

    char path[128];
    contract_app_path(app, path, (int)sizeof(path));

    char *av[24];
    int ac = 0;
    av[ac++] = path;
    av[ac++] = (char *)"--contract";
    for (int i = 0; i < argc && ac < 22; i++) av[ac++] = argv[i];
    av[ac] = 0;

    char cap[192];
    if (userhome_path(0, "CTL.OUT", cap, sizeof(cap)) != 0)
        strlcpy(cap, CT_TMP_FALLBACK, sizeof(cap));

    unlink(cap);
    int pid = sys_spawn_redir(path, av, ac, 0, cap, 0);
    if (pid < 0) {
        strlcpy(cap, CT_TMP_FALLBACK, sizeof(cap));
        unlink(cap);
        pid = sys_spawn_redir(path, av, ac, 0, cap, 0);
    }
    if (pid < 0) {
        // Last resort: no capture. The app still answers, and its stdout still
        // reaches the serial console through the kernel's fd-1 fallback, so a
        // harness reading the serial socket still gets the result. The CALLER
        // gets nothing back, which is why this is last and not first.
        pid = sys_spawn_args(path, av, ac);
        if (pid < 0) {
            snprintf(out, ocap, "err code=usage detail=cannot-spawn path=%s\n", path);
            return CT_ERR_USAGE;
        }
        int st2 = 0;
        sys_waitpid(pid, &st2, 0);
        snprintf(out, ocap, "err code=failed detail=no-writable-capture-path path=%s\n", path);
        return st2 == 0 ? CT_OK : CT_ERR_FAILED;
    }

    int status = 0;
    sys_waitpid(pid, &status, 0);

    int fd = open(cap, O_RDONLY);
    if (fd < 0) {
        snprintf(out, ocap, "err code=failed detail=no-output path=%s exit=%d\n", path, status);
        return CT_ERR_FAILED;
    }
    int used = 0;
    for (;;) {
        if (used >= ocap - 1) break;
        long n = read(fd, out + used, (size_t)(ocap - 1 - used));
        if (n <= 0) break;
        used += (int)n;
    }
    close(fd);
    unlink(cap);
    if (ocap > 0) out[used < ocap ? used : ocap - 1] = 0;

    // The app's exit status IS the answer's code. We do not reinterpret its
    // text: a caller that paraphrased would be a second description of the
    // result, which is the class of thing this API exists to delete.
    return status;
}
