#ifndef _MAYTERA_TREMOR_SYS_TYPES_H
#define _MAYTERA_TREMOR_SYS_TYPES_H
#ifndef LITTLE_ENDIAN
#define LITTLE_ENDIAN 1234
#endif
#ifndef BIG_ENDIAN
#define BIG_ENDIAN 4321
#endif
#ifndef BYTE_ORDER
#define BYTE_ORDER LITTLE_ENDIAN
#endif
#endif
