// boot_image.h - the compiled-in boot splash (#703).
//
// The splash is drawn by gfx_draw_boot_image() BEFORE the filesystem is mounted,
// which is why it cannot simply become a file on disk. It does not have to be
// uncompressed, though, and it was: 640*400*3 = 768,000 bytes of RGB in .rodata,
// 18.2% of the entire linked kernel, for an image in which every pixel has
// R == G == B.
//
// It is now an 8-bit grey plane, PNG-filtered per scanline, in a raw DEFLATE
// stream, regenerated by tools/gen-boot-splash.py. video/graphics.c inflates and
// unfilters it once into .bss (which costs no file bytes) using the DEFLATE core
// and PNG scanline unfilterer the kernel already carries. Neither needs the
// filesystem or the heap, so the pre-mount constraint is preserved. The decode is
// bit-exact against the old array: same pixels, 139,267 bytes instead of 768,000.
#ifndef BOOT_IMAGE_H
#define BOOT_IMAGE_H

#include "../types.h"

#define BOOT_IMAGE_WIDTH 640
#define BOOT_IMAGE_HEIGHT 400

// The compiled-in blob (generated).
extern const uint8_t boot_image_deflate[];
extern const uint32_t boot_image_deflate_len;     // bytes of DEFLATE
extern const uint32_t boot_image_filtered_len;    // (WIDTH+1)*HEIGHT after inflate

// One BOOT_IMAGE_WIDTH*BOOT_IMAGE_HEIGHT 8-bit grey plane, decoded on first call
// and cached, or NULL if the blob failed to decode (caller falls back to the
// gradient). Safe pre-mount; allocates nothing.
const uint8_t *boot_image_gray(void);

#endif // BOOT_IMAGE_H
