#!/usr/bin/env bash
# robots/build.sh - see PORT for why build=script.
set -euo pipefail

PORT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
S="${MPORTS_SRC:?robots/build.sh: MPORTS_SRC unset}"
W="$(dirname "$(dirname "$S")")"
WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

# pathnames.h: upstream ships only pathnames.h.in. score.c opens this
# read/write, non-fatally on failure (see PORT's SCOREFILE HONESTY note), so
# a writable per-user path is enough; matches the moon-buggy port's SCORE_DIR
# "/HOME" precedent (userland/ports/moonbuggy/build.sh).
echo "robots/build.sh: writing pathnames.h"
cat > pathnames.h <<'EOF'
/* generated by userland/ports/robots/build.sh - no configure is run here. */
#define _PATH_SCORE "/HOME/.robots.scores"
EOF

CFLAGS="$MPORTS_CFLAGS -I$PORT_DIR/shim -DBSDGAME_PROGNAME=\"robots\" -DFANCY -DMAX_PER_UID=5 -w"

SRCS="main auto extern flush_in init_field make_level move move_robs play_level query rnd_pos score"
for f in $SRCS; do
  gcc $CFLAGS -c "$f.c" -o "$WORKDIR/rb_$f.o"
done
gcc $CFLAGS -c "$PORT_DIR/bsdgame_compat.c" -o "$WORKDIR/rb_compat.o"

rm -f "$W/librobots.a"
ar rcs "$W/librobots.a" "$WORKDIR"/rb_*.o
echo "robots/build.sh: OK -> $W/librobots.a"
