/* GENERATED by tools/pcre2-oracle/gen_expect.py - do not hand-edit.
 *
 * Ground truth for userland/apps/pcre2check. Every expected value below was
 * produced by Debian's libpcre2-8 10.42 (a DIFFERENT version, toolchain and
 * build configuration from userland/ports/pcre2) and then diffed, case for
 * case, against Python 3.11's `re`. The generator REFUSES to emit a case the
 * two oracles disagree about, so no expectation here is a hand-written guess
 * and none of it is self-consistency with our own build.
 *
 * The one case the two oracles could not both cover is "posix class":
 * Python's re has no POSIX bracket expressions. Its second opinion is GNU
 * grep -obE, which reports offset 3 length 3, matching pcre2 exactly.
 */
#ifndef PCRE2CHECK_EXPECT_H
#define PCRE2CHECK_EXPECT_H

#define EXP_MAXG 8

typedef struct {
    const char *name;
    const char *pat;
    unsigned    opt;      /* PCRE2_* option bits, resolved in main.c */
    const char *subj;
    unsigned    subjlen;
    int         rc;       /* expected pcre2_match() return */
    int         ov[EXP_MAXG*2]; /* expected ovector pairs; -2 = unset */
    const char *oracle;   /* which independent implementations agreed */
} exp_case_t;

static const exp_case_t EXPECT[] = {
    { "anchored digits", "^\\d{3}-\\d{4}$", 0, "555-1234", 8, 1,
      { 0, 8, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
    { "no match", "^\\d{3}-\\d{4}$", 0, "5551234", 7, -1,
      { -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
    { "two captures", "(\\w+)@(\\w+)\\.com", 0, "mail bob@example.com now", 24, 3,
      { 5, 20, 5, 8, 9, 16, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
    { "backreference", "(\\w+) \\1", 0, "say hello hello world", 21, 2,
      { 4, 15, 4, 9, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
    { "backref no match", "(\\w+) \\1", 0, "say hello world twice", 21, -1,
      { -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
    { "lazy quantifier", "<(.+?)>", 0, "<a><b>", 6, 2,
      { 0, 3, 1, 2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
    { "greedy quantifier", "<(.+)>", 0, "<a><b>", 6, 2,
      { 0, 6, 1, 5, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
    { "alternation anchored", "^(foo|bar)baz$", 0, "barbaz", 6, 2,
      { 0, 6, 0, 3, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
    { "caseless", "hello", PCRE2_CASELESS, "say HeLLo there", 15, 1,
      { 4, 9, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
    { "named groups", "(?P<year>\\d{4})-(?P<mon>\\d{2})", 0, "on 2026-08-13", 13, 3,
      { 3, 10, 3, 7, 8, 10, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
    { "lookahead", "foo(?=bar)", 0, "foobar foobaz", 13, 1,
      { 0, 3, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
    { "negative lookahead", "foo(?!bar)", 0, "foobar foobaz", 13, 1,
      { 7, 10, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
    { "negative lookbehind", "(?<!x)y", 0, "xy zy", 5, 1,
      { 4, 5, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
    { "word boundary hit", "\\bcat\\b", 0, "the cat sat", 11, 1,
      { 4, 7, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
    { "word boundary miss", "\\bcat\\b", 0, "concatenate", 11, -1,
      { -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
    { "posix class", "[[:alpha:]]+", 0, "123abc456", 9, 1,
      { 3, 6, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + GNU grep -obE" },
    { "optional char", "colou?r", 0, "the color red", 13, 1,
      { 4, 9, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
    { "nested groups", "((a)(b))c", 0, "xabc", 4, 4,
      { 1, 4, 1, 3, 1, 2, 2, 3, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
    { "multiline anchor", "^b", PCRE2_MULTILINE, "a\nb\nc", 5, 1,
      { 2, 3, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
    { "dotall", "a.b", PCRE2_DOTALL, "xa\nby", 5, 1,
      { 1, 4, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
    { "dot without dotall", "a.b", 0, "xa\nby", 5, -1,
      { -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
    { "char class range", "[a-f]+", 0, "xyzabcdefg", 10, 1,
      { 3, 9, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
    { "negated class", "[^0-9]+", 0, "42abc", 5, 1,
      { 2, 5, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
    { "bounded repeat", "a{2,4}", 0, "baaaaaa", 7, 1,
      { 1, 5, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
    { "empty capture", "(x?)y", 0, "zy", 2, 2,
      { 1, 2, 1, 1, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2 }, "pcre2-10.42 + python3.11-re" },
};
#define EXPECT_N 25

#endif
