// pcre2check - proof that the mports-built real PCRE2 (userland/ports/pcre2)
// works on a running MayteraOS, not just that it compiled.
//
// This is NOT upstream's `pcre2test`: that program is a 10,000-line harness
// with its own main(), and userland/ports/pcre2/PORT excludes it by name. This
// is ours, and it is small on purpose.
//
// WHY THIS APP EXISTS. "A library that compiles but was never linked and run is
// not evidence." This is the evidence. It links the static libpcre2-8.a that
// userland/ports/mports.sh produced from the sha256-pinned upstream tarball,
// and it runs on a booted machine.
//
// THE EXPECTATIONS ARE NOT OURS. expect.h is generated by
// tools/pcre2-oracle/gen_expect.py from TWO independent implementations that
// were made to agree first:
//
//   * Debian's libpcre2-8 10.42, a different version built by a different
//     toolchain with a different config.h from the one this port builds;
//   * Python 3.11's `re`, a completely separate implementation.
//
// The generator refuses to emit any case the two disagree about, so there is no
// hand-written expectation anywhere in this app. That matters because a
// hand-written expectation for someone else's specification is a guess with a
// straight face (blame.md, the getopt `--` incident), and because a codec or
// matcher that is merely self-consistent is exactly what the two hand-written
// zlib shims were.
//
// The two build-configuration decisions in userland/ports/pcre2 are also
// asserted here, so that they are TESTED FACTS rather than claims in a comment:
// the JIT is genuinely absent (not merely unused) and asking for Unicode fails
// LOUDLY rather than silently matching something else.
//
// OUTPUT DISCIPLINE. Launched via /CONFIG/AUTORUN.CFG containing
// "/APPS/PCRE2CHK". An autorun-launched process emits ONE SERIAL RECORD PER
// write(), so a line assembled from several write() calls arrives as several
// interleaved fragments (blame.md, #700). Every line here is formatted into a
// buffer and issued as exactly one write(2, ...).

#include "stdlib.h"
#include "string.h"
#include "stdio.h"
#include "unistd.h"

#define PCRE2_CODE_UNIT_WIDTH 8
#include "pcre2.h"

#include "expect.h"

static int g_pass = 0, g_fail = 0;

static void line(const char *s) { write(2, s, strlen(s)); }

static void ck(const char *what, int ok) {
    char b[320];
    if (ok) g_pass++; else g_fail++;
    snprintf(b, sizeof(b), "[PCRE2CHK] %s %s\n", ok ? "PASS" : "FAIL", what);
    line(b);
}

int main(void) {
    char b[512];
    unsigned i;
    int rc;

    line("[PCRE2CHK] ==== mports PCRE2 proof, start ====\n");

    // --- identity: which library is actually linked in ----------------------
    {
        char ver[128];
        int n = pcre2_config(PCRE2_CONFIG_VERSION, ver);
        (void)n;
        snprintf(b, sizeof(b), "[PCRE2CHK] pcre2_config(VERSION)=%s PCRE2_MAJOR=%d PCRE2_MINOR=%d\n",
                 ver, PCRE2_MAJOR, PCRE2_MINOR);
        line(b);
        ck("linked library reports version 10.45", PCRE2_MAJOR == 10 && PCRE2_MINOR == 45);
    }

    // --- the two build decisions, asserted at RUNTIME ------------------------
    // A decision recorded only in a comment is a claim. These make it a fact.
    {
        uint32_t jit = 1, uni = 1;
        pcre2_config(PCRE2_CONFIG_JIT, &jit);
        pcre2_config(PCRE2_CONFIG_UNICODE, &uni);
        snprintf(b, sizeof(b), "[PCRE2CHK] config: JIT=%u UNICODE=%u\n",
                 (unsigned)jit, (unsigned)uni);
        line(b);
        ck("JIT is NOT compiled in (W^X: sljit maps one PROT_WRITE|PROT_EXEC region "
           "and this kernel has no mprotect)", jit == 0);
        ck("Unicode is NOT compiled in (measured 490KB of tables; see the port recipe)",
           uni == 0);
    }
    {
        // The JIT stub must still be LINKED, or "the JIT is off" would be
        // indistinguishable from "pcre2_jit_compile.c was quietly dropped".
        int err; PCRE2_SIZE eoff;
        pcre2_code *re = pcre2_compile((PCRE2_SPTR)"abc", PCRE2_ZERO_TERMINATED, 0,
                                       &err, &eoff, NULL);
        ck("a trivial pattern compiles at all", re != NULL);
        if (re) {
            rc = pcre2_jit_compile(re, PCRE2_JIT_COMPLETE);
            snprintf(b, sizeof(b), "[PCRE2CHK]      pcre2_jit_compile() -> %d "
                     "(PCRE2_ERROR_JIT_BADOPTION=%d)\n", rc, PCRE2_ERROR_JIT_BADOPTION);
            line(b);
            ck("pcre2_jit_compile() is linked and refuses with JIT_BADOPTION",
               rc == PCRE2_ERROR_JIT_BADOPTION);
            pcre2_code_free(re);
        }
    }
    {
        // Asking for UTF must FAIL, and fail with the specific code, not just
        // "some error". A silent fallback would be the dangerous outcome.
        int err = 0; PCRE2_SIZE eoff = 0;
        pcre2_code *re = pcre2_compile((PCRE2_SPTR)"abc", PCRE2_ZERO_TERMINATED,
                                       PCRE2_UTF, &err, &eoff, NULL);
        snprintf(b, sizeof(b), "[PCRE2CHK]      compile(PCRE2_UTF) -> code=%p err=%d "
                 "(PCRE2_ERROR_UNICODE_NOT_SUPPORTED=%d)\n",
                 (void *)re, err, PCRE2_ERROR_UNICODE_NOT_SUPPORTED);
        line(b);
        ck("PCRE2_UTF is refused LOUDLY with UNICODE_NOT_SUPPORTED, not silently ignored",
           re == NULL && err == PCRE2_ERROR_UNICODE_NOT_SUPPORTED);
        if (re) pcre2_code_free(re);
    }

    // --- the corpus, against two independent implementations -----------------
    for (i = 0; i < EXPECT_N; i++) {
        const exp_case_t *c = &EXPECT[i];
        int err = 0; PCRE2_SIZE eoff = 0;
        pcre2_code *re;
        pcre2_match_data *md;
        PCRE2_SIZE *ov;
        int ok = 1, k;

        re = pcre2_compile((PCRE2_SPTR)c->pat, PCRE2_ZERO_TERMINATED, c->opt,
                           &err, &eoff, NULL);
        if (re == NULL) {
            PCRE2_UCHAR msg[160];
            pcre2_get_error_message(err, msg, sizeof(msg));
            snprintf(b, sizeof(b), "[PCRE2CHK]      compile failed for %s: %s (offset %d)\n",
                     c->name, (const char *)msg, (int)eoff);
            line(b);
            ck(c->name, 0);
            continue;
        }
        md = pcre2_match_data_create_from_pattern(re, NULL);
        rc = pcre2_match(re, (PCRE2_SPTR)c->subj, c->subjlen, 0, 0, md, NULL);
        if (rc != c->rc) ok = 0;
        if (rc > 0) {
            ov = pcre2_get_ovector_pointer(md);
            for (k = 0; k < rc && k < EXP_MAXG; k++) {
                int es = c->ov[2*k], ee = c->ov[2*k+1];
                if (es == -2) {
                    if (ov[2*k] != PCRE2_UNSET) ok = 0;
                } else {
                    if ((int)ov[2*k] != es || (int)ov[2*k+1] != ee) ok = 0;
                }
            }
        }
        snprintf(b, sizeof(b), "[PCRE2CHK]      %-22s rc=%d want=%d%s  [%s]\n",
                 c->name, rc, c->rc, ok ? "" : "  <-- MISMATCH", c->oracle);
        line(b);
        if (!ok && rc > 0) {
            ov = pcre2_get_ovector_pointer(md);
            for (k = 0; k < rc && k < EXP_MAXG; k++) {
                snprintf(b, sizeof(b), "[PCRE2CHK]        group %d got=%d,%d want=%d,%d\n",
                         k, (int)ov[2*k], (int)ov[2*k+1], c->ov[2*k], c->ov[2*k+1]);
                line(b);
            }
        }
        ck(c->name, ok);
        pcre2_match_data_free(md);
        pcre2_code_free(re);
    }

    // --- substring extraction, by number and by name -------------------------
    {
        const char *subj = "on 2026-08-13 at noon";
        int err = 0; PCRE2_SIZE eoff = 0;
        pcre2_code *re = pcre2_compile((PCRE2_SPTR)"(?P<year>\\d{4})-(?P<mon>\\d{2})",
                                       PCRE2_ZERO_TERMINATED, 0, &err, &eoff, NULL);
        ck("named-group pattern compiles", re != NULL);
        if (re) {
            pcre2_match_data *md = pcre2_match_data_create_from_pattern(re, NULL);
            rc = pcre2_match(re, (PCRE2_SPTR)subj, strlen(subj), 0, 0, md, NULL);
            ck("named-group pattern matches with 3 ovector pairs", rc == 3);
            {
                PCRE2_UCHAR out[32]; PCRE2_SIZE olen = sizeof(out);
                int n = pcre2_substring_number_from_name(re, (PCRE2_SPTR)"mon");
                snprintf(b, sizeof(b), "[PCRE2CHK]      substring_number_from_name(\"mon\")=%d\n", n);
                line(b);
                ck("the name 'mon' resolves to group 2", n == 2);
                olen = sizeof(out);
                rc = pcre2_substring_copy_bynumber(md, 1, out, &olen);
                snprintf(b, sizeof(b), "[PCRE2CHK]      group 1 = '%s' (rc=%d)\n",
                         (const char *)out, rc);
                line(b);
                ck("group 1 extracts as the string \"2026\"",
                   rc == 0 && strcmp((const char *)out, "2026") == 0);
                olen = sizeof(out);
                rc = pcre2_substring_copy_bynumber(md, 2, out, &olen);
                ck("group 2 extracts as the string \"08\"",
                   rc == 0 && strcmp((const char *)out, "08") == 0);
            }
            pcre2_match_data_free(md);
            pcre2_code_free(re);
        }
    }

    // --- pcre2_substitute ----------------------------------------------------
    {
        const char *subj = "mail bob@example now";
        PCRE2_UCHAR out[128]; PCRE2_SIZE olen = sizeof(out);
        int err = 0; PCRE2_SIZE eoff = 0;
        pcre2_code *re = pcre2_compile((PCRE2_SPTR)"(\\w+)@(\\w+)", PCRE2_ZERO_TERMINATED,
                                       0, &err, &eoff, NULL);
        ck("substitution pattern compiles", re != NULL);
        if (re) {
            rc = pcre2_substitute(re, (PCRE2_SPTR)subj, strlen(subj), 0, 0, NULL, NULL,
                                  (PCRE2_SPTR)"$2 at $1", PCRE2_ZERO_TERMINATED,
                                  out, &olen);
            snprintf(b, sizeof(b), "[PCRE2CHK]      substitute -> rc=%d '%s'\n",
                     rc, (const char *)out);
            line(b);
            ck("pcre2_substitute() rewrites the capture order to \"mail example at bob now\"",
               rc == 1 && strcmp((const char *)out, "mail example at bob now") == 0);
            pcre2_code_free(re);
        }
    }

    // --- the alternative matcher: pcre2_dfa_match ---------------------------
    // A different engine in the same archive. It has no backreference support,
    // so it is exercised on a pattern that does not need one.
    {
        const char *subj = "xxabcdyy";
        int err = 0; PCRE2_SIZE eoff = 0;
        int wsp[64];
        pcre2_code *re = pcre2_compile((PCRE2_SPTR)"ab(c|cd)", PCRE2_ZERO_TERMINATED,
                                       0, &err, &eoff, NULL);
        ck("dfa pattern compiles", re != NULL);
        if (re) {
            pcre2_match_data *md = pcre2_match_data_create(8, NULL);
            rc = pcre2_dfa_match(re, (PCRE2_SPTR)subj, strlen(subj), 0, 0, md, NULL,
                                 wsp, (PCRE2_SIZE)(sizeof(wsp)/sizeof(wsp[0])));
            PCRE2_SIZE *ov = pcre2_get_ovector_pointer(md);
            snprintf(b, sizeof(b), "[PCRE2CHK]      dfa_match rc=%d longest=%d..%d\n",
                     rc, rc > 0 ? (int)ov[0] : -1, rc > 0 ? (int)ov[1] : -1);
            line(b);
            // The DFA matcher returns ALL alternatives, longest first: "abcd"
            // then "abc". That is the documented difference from pcre2_match,
            // which returns only the leftmost-first "abc".
            ck("pcre2_dfa_match() returns 2 alternatives, longest 2..6 = \"abcd\"",
               rc == 2 && (int)ov[0] == 2 && (int)ov[1] == 6);
            pcre2_match_data_free(md);
            pcre2_code_free(re);
        }
    }

    // --- allocator plumbing: the caller can own the memory -------------------
    // This is the concrete form of the adoption test. If PCRE2 wanted to BE the
    // platform it could not hand its allocator to us.
    {
        pcre2_general_context *gc = pcre2_general_context_create(NULL, NULL, NULL);
        ck("pcre2_general_context_create() with the default allocator works", gc != NULL);
        if (gc) pcre2_general_context_free(gc);
    }

    snprintf(b, sizeof(b), "[PCRE2CHK] ==== done: %d passed, %d failed ====\n",
             g_pass, g_fail);
    line(b);
    line(g_fail == 0 ? "[PCRE2CHK] RESULT OK\n" : "[PCRE2CHK] RESULT FAILED\n");
    return g_fail == 0 ? 0 : 1;
}
