#!/usr/bin/env bash
# ports/libedit/build.sh - the build=script body for the libedit port (#745).
#
# WHY THIS IS A SCRIPT AND NOT build=objects. libedit is an autotools+libtool
# project and part of its library source is GENERATED by the makelist awk/sh
# generator at build time (vi.h, emacs.h, common.h, fcns.h, help.h, func.h from
# the *.c command tables). The honest way to track that is to let upstream's own
# build system produce it, so a version bump is a change to the sha256 pin and
# nothing else. mports still enforces the outcome: PORT lists lib=libedit.a and
# the symbols it must contain, and mports fails the build unless the archive
# exists and every one of those symbols is DEFINED in it.
#
# CROSS-COMPILE MODEL, same as ncurses. The MayteraOS "cross toolchain" is the
# host gcc plus the freestanding userland flag set (ports.mk), not a separate
# triple, so configure runs with --host != --build (its generators run on the
# host, the library compiles with our target flags) and its link-based probes
# are made honest by pointing LIBS at userland/libc's crt0.o + libc.a.
#
# THREE THINGS THIS BUILD TELLS CONFIGURE THAT A PURE PROBE COULD NOT:
#   * ac_cv_lib_ncurses_tgetent=yes - the termcap interface lives in the ncurses
#     we built (tgetent/tgetstr are defined in libncurses.a even though ncurses
#     was configured --disable-termcap; that flag only removes the /etc/termcap
#     file fallback, not the emulation entry points). A -nostdlib cross link
#     probe is too fragile to trust here, so it is asserted.
#   * -D__STDC_ISO_10646__ - src/chartype.h #errors without it. Our wchar_t
#     values 0..0x7f are ASCII/ISO-10646-compatible, which is all libedit relies
#     on; the define states that truthfully.
#   * -include sys/types.h - libedit's sys.h declares getline() with ssize_t but
#     only includes <stdio.h>, which does not pull ssize_t on this libc.
#
# regex.h and curses.h/term.h/termcap.h are found via -I$OUT/include (the
# musl-regex and ncurses ports installed them there); needs= guarantees both are
# built first.

set -euo pipefail

S="${MPORTS_SRC:?libedit/build.sh: MPORTS_SRC unset}"      # unpacked+patched srcdir
OUT="${MPORTS_OUT:?libedit/build.sh: MPORTS_OUT unset}"    # ports/out
CFBASE="${MPORTS_CFLAGS:?libedit/build.sh: MPORTS_CFLAGS unset}"  # target compile profile
W="$(dirname "$S")"                          # ports/.work/libedit (mports wants lib at $W/<lib>)
LIBC="$(realpath -m "$OUT/../../libc")"       # userland/libc (realpath -m: no existence needed)
BUILDTRIPLE="$(sh "$S/config.guess")"
NPROC="$(nproc 2>/dev/null || echo 2)"

# Defensive: a build=script port built FIRST in a fresh tree can run before
# mports has created out/ (it creates the include/lib dirs after this script).
mkdir -p "$OUT/include" "$OUT/lib"

# The two additions the freestanding profile needs for libedit specifically.
CF="$CFBASE -D__STDC_ISO_10646__=201103L -include sys/types.h"

echo "libedit/build.sh: S=$S OUT=$OUT LIBC=$LIBC build-triple=$BUILDTRIPLE"

[ -f "$OUT/lib/libncurses.a" ] || { echo "libedit/build.sh: libncurses.a missing in $OUT/lib (ncurses needs= not built?)"; exit 1; }
[ -f "$OUT/lib/libregex.a" ]   || { echo "libedit/build.sh: libregex.a missing in $OUT/lib (musl-regex needs= not built?)"; exit 1; }

TB="$W/build"; rm -rf "$TB"; mkdir -p "$TB"; cd "$TB"
"$S/configure" \
  --host=x86_64-pc-none --build="$BUILDTRIPLE" \
  CC=gcc CFLAGS="$CF" CPPFLAGS="$CF -I$OUT/include" \
  LDFLAGS="-nostdlib -static -L$OUT/lib" LIBS="$LIBC/crt0.o $LIBC/libc.a" \
  AR=ar RANLIB=ranlib AWK=awk \
  ac_cv_lib_ncurses_tgetent=yes \
  --disable-shared --enable-static --disable-examples \
  >configure.log 2>&1 || { echo "libedit/build.sh: configure FAILED"; tail -40 configure.log; exit 1; }

# make LIBS= : the objects compile with the Makefile's own (target) CFLAGS; LIBS
# is emptied ONLY for the final libtool step, because a static-archive link that
# carries the non-libtool crt0.o/libc.a we set for configure's probes makes
# libtool refuse ("cannot build libtool library from non-libtool objects"). The
# archive is just ar over the compiled objects; it needs no LIBS.
make -j"$NPROC" LIBS= >make.log 2>&1 || { echo "libedit/build.sh: make FAILED"; tail -50 make.log; exit 1; }

ARCHIVE=""
for cand in "$TB/src/.libs/libedit.a" "$TB/src/libedit.a"; do
  [ -f "$cand" ] && { ARCHIVE="$cand"; break; }
done
[ -n "$ARCHIVE" ] || { echo "libedit/build.sh: no libedit.a produced"; find "$TB" -name 'libedit*.a'; exit 1; }

# Primary lib where mports expects it (it symbol-checks and installs $W/<lib>).
cp "$ARCHIVE" "$W/libedit.a"

# The readline-compat header, alongside the histedit.h that mports installs via
# headers=. A consumer using <editline/readline.h> gets it here.
mkdir -p "$OUT/include/editline"
cp "$S/src/editline/readline.h" "$OUT/include/editline/readline.h"

echo "libedit/build.sh: libedit.a built ($(wc -c < "$W/libedit.a") bytes) from $ARCHIVE"
