// cursor.c - Cursor system implementation for MayteraOS
#include "cursor.h"
#include "../types.h"
#include "../serial.h"
#include "../video/framebuffer.h"

// ============================================================================
// Retro-Style Cursor Bitmaps (16x16, 1-bit with mask)
// Classic X11/Windows 3.1 style - sharp, pixel-perfect
// ============================================================================

// Default Arrow Cursor (16x16)
static const uint8_t retro_arrow_image[] = {
    0x00, 0x00,  // ................
    0x40, 0x00,  // .X..............
    0x60, 0x00,  // .XX.............
    0x70, 0x00,  // .XXX............
    0x78, 0x00,  // .XXXX...........
    0x7C, 0x00,  // .XXXXX..........
    0x7E, 0x00,  // .XXXXXX.........
    0x7F, 0x00,  // .XXXXXXX........
    0x7F, 0x80,  // .XXXXXXXX.......
    0x7C, 0x00,  // .XXXXX..........
    0x6C, 0x00,  // .XX.XX..........
    0x46, 0x00,  // .X...XX.........
    0x06, 0x00,  // .....XX.........
    0x03, 0x00,  // ......XX........
    0x03, 0x00,  // ......XX........
    0x00, 0x00,  // ................
};

static const uint8_t retro_arrow_mask[] = {
    0xC0, 0x00,  // XX..............
    0xE0, 0x00,  // XXX.............
    0xF0, 0x00,  // XXXX............
    0xF8, 0x00,  // XXXXX...........
    0xFC, 0x00,  // XXXXXX..........
    0xFE, 0x00,  // XXXXXXX.........
    0xFF, 0x00,  // XXXXXXXX........
    0xFF, 0x80,  // XXXXXXXXX.......
    0xFF, 0xC0,  // XXXXXXXXXX......
    0xFF, 0x80,  // XXXXXXXXX.......
    0xFE, 0x00,  // XXXXXXX.........
    0xEF, 0x00,  // XXX.XXXX........
    0x4F, 0x00,  // .X..XXXX........
    0x07, 0x80,  // .....XXXX.......
    0x07, 0x80,  // .....XXXX.......
    0x03, 0x00,  // ......XX........
};

// I-Beam Text Cursor (16x16)
static const uint8_t retro_ibeam_image[] = {
    0x00, 0x00,  // ................
    0x6C, 0x00,  // .XX.XX..........
    0x10, 0x00,  // ...X............
    0x10, 0x00,  // ...X............
    0x10, 0x00,  // ...X............
    0x10, 0x00,  // ...X............
    0x10, 0x00,  // ...X............
    0x10, 0x00,  // ...X............
    0x10, 0x00,  // ...X............
    0x10, 0x00,  // ...X............
    0x10, 0x00,  // ...X............
    0x10, 0x00,  // ...X............
    0x10, 0x00,  // ...X............
    0x6C, 0x00,  // .XX.XX..........
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
};

static const uint8_t retro_ibeam_mask[] = {
    0xFE, 0x00,  // XXXXXXX.........
    0xFE, 0x00,  // XXXXXXX.........
    0x38, 0x00,  // ..XXX...........
    0x38, 0x00,  // ..XXX...........
    0x38, 0x00,  // ..XXX...........
    0x38, 0x00,  // ..XXX...........
    0x38, 0x00,  // ..XXX...........
    0x38, 0x00,  // ..XXX...........
    0x38, 0x00,  // ..XXX...........
    0x38, 0x00,  // ..XXX...........
    0x38, 0x00,  // ..XXX...........
    0x38, 0x00,  // ..XXX...........
    0x38, 0x00,  // ..XXX...........
    0xFE, 0x00,  // XXXXXXX.........
    0xFE, 0x00,  // XXXXXXX.........
    0x00, 0x00,  // ................
};

// Hand/Pointer Cursor (16x16)
static const uint8_t retro_hand_image[] = {
    0x0C, 0x00,  // ....XX..........
    0x12, 0x00,  // ...X..X.........
    0x12, 0x00,  // ...X..X.........
    0x12, 0x00,  // ...X..X.........
    0x12, 0x00,  // ...X..X.........
    0x13, 0x80,  // ...X..XXX.......
    0x36, 0xC0,  // ..XX.XX.XX......
    0x49, 0x20,  // .X..X..X..X.....
    0x49, 0x20,  // .X..X..X..X.....
    0x49, 0x00,  // .X..X..X........
    0x78, 0x00,  // .XXXX...........
    0x40, 0x00,  // .X..............
    0x40, 0x00,  // .X..............
    0x20, 0x00,  // ..X.............
    0x20, 0x00,  // ..X.............
    0x00, 0x00,  // ................
};

static const uint8_t retro_hand_mask[] = {
    0x1E, 0x00,  // ...XXXX.........
    0x3F, 0x00,  // ..XXXXXX........
    0x3F, 0x00,  // ..XXXXXX........
    0x3F, 0x00,  // ..XXXXXX........
    0x3F, 0xC0,  // ..XXXXXXXX......
    0x7F, 0xE0,  // .XXXXXXXXXX.....
    0xFF, 0xF0,  // XXXXXXXXXXXX....
    0xFF, 0xF0,  // XXXXXXXXXXXX....
    0xFF, 0xF0,  // XXXXXXXXXXXX....
    0xFF, 0xE0,  // XXXXXXXXXXX.....
    0xFC, 0x00,  // XXXXXX..........
    0xFC, 0x00,  // XXXXXX..........
    0xF0, 0x00,  // XXXX............
    0x70, 0x00,  // .XXX............
    0x70, 0x00,  // .XXX............
    0x20, 0x00,  // ..X.............
};

// Wait/Hourglass Cursor (16x16)
static const uint8_t retro_wait_image[] = {
    0x7F, 0xE0,  // .XXXXXXXXXX.....
    0x40, 0x20,  // .X........X.....
    0x20, 0x40,  // ..X......X......
    0x10, 0x80,  // ...X....X.......
    0x09, 0x00,  // ....X..X........
    0x06, 0x00,  // .....XX.........
    0x06, 0x00,  // .....XX.........
    0x06, 0x00,  // .....XX.........
    0x06, 0x00,  // .....XX.........
    0x09, 0x00,  // ....X..X........
    0x10, 0x80,  // ...X....X.......
    0x20, 0x40,  // ..X......X......
    0x40, 0x20,  // .X........X.....
    0x7F, 0xE0,  // .XXXXXXXXXX.....
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
};

static const uint8_t retro_wait_mask[] = {
    0xFF, 0xF0,  // XXXXXXXXXXXX....
    0xFF, 0xF0,  // XXXXXXXXXXXX....
    0x7F, 0xE0,  // .XXXXXXXXXX.....
    0x3F, 0xC0,  // ..XXXXXXXX......
    0x1F, 0x80,  // ...XXXXXX.......
    0x0F, 0x00,  // ....XXXX........
    0x0F, 0x00,  // ....XXXX........
    0x0F, 0x00,  // ....XXXX........
    0x0F, 0x00,  // ....XXXX........
    0x1F, 0x80,  // ...XXXXXX.......
    0x3F, 0xC0,  // ..XXXXXXXX......
    0x7F, 0xE0,  // .XXXXXXXXXX.....
    0xFF, 0xF0,  // XXXXXXXXXXXX....
    0xFF, 0xF0,  // XXXXXXXXXXXX....
    0x7F, 0xE0,  // .XXXXXXXXXX.....
    0x00, 0x00,  // ................
};

// North-South Resize Cursor (16x16)
static const uint8_t retro_resize_ns_image[] = {
    0x02, 0x00,  // ......X.........
    0x07, 0x00,  // .....XXX........
    0x0F, 0x80,  // ....XXXXX.......
    0x02, 0x00,  // ......X.........
    0x02, 0x00,  // ......X.........
    0x02, 0x00,  // ......X.........
    0x02, 0x00,  // ......X.........
    0x02, 0x00,  // ......X.........
    0x02, 0x00,  // ......X.........
    0x02, 0x00,  // ......X.........
    0x02, 0x00,  // ......X.........
    0x02, 0x00,  // ......X.........
    0x0F, 0x80,  // ....XXXXX.......
    0x07, 0x00,  // .....XXX........
    0x02, 0x00,  // ......X.........
    0x00, 0x00,  // ................
};

static const uint8_t retro_resize_ns_mask[] = {
    0x07, 0x00,  // .....XXX........
    0x0F, 0x80,  // ....XXXXX.......
    0x1F, 0xC0,  // ...XXXXXXX......
    0x0F, 0x80,  // ....XXXXX.......
    0x07, 0x00,  // .....XXX........
    0x07, 0x00,  // .....XXX........
    0x07, 0x00,  // .....XXX........
    0x07, 0x00,  // .....XXX........
    0x07, 0x00,  // .....XXX........
    0x07, 0x00,  // .....XXX........
    0x07, 0x00,  // .....XXX........
    0x0F, 0x80,  // ....XXXXX.......
    0x1F, 0xC0,  // ...XXXXXXX......
    0x0F, 0x80,  // ....XXXXX.......
    0x07, 0x00,  // .....XXX........
    0x02, 0x00,  // ......X.........
};

// East-West Resize Cursor (16x16)
static const uint8_t retro_resize_ew_image[] = {
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
    0x04, 0x40,  // .....X...X......
    0x0C, 0x60,  // ....XX...XX.....
    0x1F, 0xF0,  // ...XXXXXXXXX....
    0x0C, 0x60,  // ....XX...XX.....
    0x04, 0x40,  // .....X...X......
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
};

static const uint8_t retro_resize_ew_mask[] = {
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
    0x0C, 0x60,  // ....XX...XX.....
    0x1C, 0x70,  // ...XXX...XXX....
    0x3F, 0xF8,  // ..XXXXXXXXXXX...
    0x3F, 0xF8,  // ..XXXXXXXXXXX...
    0x3F, 0xF8,  // ..XXXXXXXXXXX...
    0x1C, 0x70,  // ...XXX...XXX....
    0x0C, 0x60,  // ....XX...XX.....
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
};

// NE-SW Diagonal Resize Cursor (16x16)
static const uint8_t retro_resize_nesw_image[] = {
    0x00, 0x00,  // ................
    0x3F, 0x00,  // ..XXXXXX........
    0x06, 0x00,  // .....XX.........
    0x0A, 0x00,  // ....X.X.........
    0x12, 0x00,  // ...X..X.........
    0x20, 0x00,  // ..X.............
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
    0x00, 0x08,  // .............X..
    0x00, 0x90,  // .........X..X...
    0x00, 0xA0,  // .........X.X....
    0x00, 0xC0,  // ........XX......
    0x01, 0xF8,  // .......XXXXXX...
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
};

static const uint8_t retro_resize_nesw_mask[] = {
    0x7F, 0x80,  // .XXXXXXXX.......
    0x7F, 0x80,  // .XXXXXXXX.......
    0x1F, 0x00,  // ...XXXXX........
    0x1F, 0x00,  // ...XXXXX........
    0x3F, 0x00,  // ..XXXXXX........
    0x77, 0x00,  // .XXX.XXX........
    0x62, 0x00,  // .XX...X.........
    0x00, 0x8C,  // ........X...XX..
    0x01, 0xDC,  // .......XXX.XXX..
    0x01, 0xF8,  // .......XXXXXX...
    0x01, 0xF0,  // .......XXXXX....
    0x01, 0xF0,  // .......XXXXX....
    0x03, 0xFC,  // ......XXXXXXXX..
    0x03, 0xFC,  // ......XXXXXXXX..
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
};

// NW-SE Diagonal Resize Cursor (16x16)
static const uint8_t retro_resize_nwse_image[] = {
    0x00, 0x00,  // ................
    0x1F, 0x80,  // ...XXXXXX.......
    0x0C, 0x00,  // ....XX..........
    0x0A, 0x00,  // ....X.X.........
    0x09, 0x00,  // ....X..X........
    0x00, 0x80,  // .........X......
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
    0x20, 0x00,  // ..X.............
    0x12, 0x00,  // ...X..X.........
    0x0A, 0x00,  // ....X.X.........
    0x06, 0x00,  // .....XX.........
    0x3F, 0x00,  // ..XXXXXX........
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
};

static const uint8_t retro_resize_nwse_mask[] = {
    0x3F, 0xC0,  // ..XXXXXXXX......
    0x3F, 0xC0,  // ..XXXXXXXX......
    0x1F, 0x00,  // ...XXXXX........
    0x1F, 0x00,  // ...XXXXX........
    0x1F, 0x80,  // ...XXXXXX.......
    0x1D, 0xC0,  // ...XXX.XXX......
    0x08, 0xC0,  // ....X...XX......
    0x62, 0x00,  // .XX...X.........
    0x77, 0x00,  // .XXX.XXX........
    0x3F, 0x00,  // ..XXXXXX........
    0x1F, 0x00,  // ...XXXXX........
    0x1F, 0x00,  // ...XXXXX........
    0x7F, 0x80,  // .XXXXXXXX.......
    0x7F, 0x80,  // .XXXXXXXX.......
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
};

// Move/Four-Way Arrow Cursor (16x16)
static const uint8_t retro_move_image[] = {
    0x00, 0x00,  // ................
    0x02, 0x00,  // ......X.........
    0x07, 0x00,  // .....XXX........
    0x0F, 0x80,  // ....XXXXX.......
    0x02, 0x00,  // ......X.........
    0x22, 0x20,  // ..X...X...X.....
    0x62, 0x30,  // .XX...X...XX....
    0xFF, 0xF8,  // XXXXXXXXXXXXX...
    0x62, 0x30,  // .XX...X...XX....
    0x22, 0x20,  // ..X...X...X.....
    0x02, 0x00,  // ......X.........
    0x0F, 0x80,  // ....XXXXX.......
    0x07, 0x00,  // .....XXX........
    0x02, 0x00,  // ......X.........
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
};

static const uint8_t retro_move_mask[] = {
    0x07, 0x00,  // .....XXX........
    0x0F, 0x80,  // ....XXXXX.......
    0x1F, 0xC0,  // ...XXXXXXX......
    0x1F, 0xC0,  // ...XXXXXXX......
    0x77, 0x70,  // .XXX.XXX.XXX....
    0xF7, 0x78,  // XXXX.XXX.XXXX...
    0xFF, 0xFC,  // XXXXXXXXXXXXXX..
    0xFF, 0xFC,  // XXXXXXXXXXXXXX..
    0xFF, 0xFC,  // XXXXXXXXXXXXXX..
    0xF7, 0x78,  // XXXX.XXX.XXXX...
    0x77, 0x70,  // .XXX.XXX.XXX....
    0x1F, 0xC0,  // ...XXXXXXX......
    0x1F, 0xC0,  // ...XXXXXXX......
    0x0F, 0x80,  // ....XXXXX.......
    0x07, 0x00,  // .....XXX........
    0x00, 0x00,  // ................
};

// Crosshair Cursor (16x16)
static const uint8_t retro_crosshair_image[] = {
    0x00, 0x00,  // ................
    0x02, 0x00,  // ......X.........
    0x02, 0x00,  // ......X.........
    0x02, 0x00,  // ......X.........
    0x02, 0x00,  // ......X.........
    0x02, 0x00,  // ......X.........
    0x02, 0x00,  // ......X.........
    0x7D, 0xF0,  // .XXXXX.XXXXX....
    0x02, 0x00,  // ......X.........
    0x02, 0x00,  // ......X.........
    0x02, 0x00,  // ......X.........
    0x02, 0x00,  // ......X.........
    0x02, 0x00,  // ......X.........
    0x02, 0x00,  // ......X.........
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
};

static const uint8_t retro_crosshair_mask[] = {
    0x07, 0x00,  // .....XXX........
    0x07, 0x00,  // .....XXX........
    0x07, 0x00,  // .....XXX........
    0x07, 0x00,  // .....XXX........
    0x07, 0x00,  // .....XXX........
    0x07, 0x00,  // .....XXX........
    0xFF, 0xF8,  // XXXXXXXXXXXXX...
    0xFF, 0xF8,  // XXXXXXXXXXXXX...
    0xFF, 0xF8,  // XXXXXXXXXXXXX...
    0x07, 0x00,  // .....XXX........
    0x07, 0x00,  // .....XXX........
    0x07, 0x00,  // .....XXX........
    0x07, 0x00,  // .....XXX........
    0x07, 0x00,  // .....XXX........
    0x07, 0x00,  // .....XXX........
    0x00, 0x00,  // ................
};

// Not-Allowed / Forbidden Cursor (16x16)
static const uint8_t retro_forbidden_image[] = {
    0x00, 0x00,  // ................
    0x0F, 0x00,  // ....XXXX........
    0x30, 0xC0,  // ..XX....XX......
    0x60, 0x60,  // .XX......XX.....
    0x40, 0xA0,  // .X......X.X.....
    0x81, 0x10,  // X......X...X....
    0x82, 0x10,  // X.....X....X....
    0x84, 0x10,  // X....X.....X....
    0x88, 0x10,  // X...X......X....
    0x50, 0x20,  // .X.X......X.....
    0x60, 0x60,  // .XX......XX.....
    0x30, 0xC0,  // ..XX....XX......
    0x0F, 0x00,  // ....XXXX........
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
};

static const uint8_t retro_forbidden_mask[] = {
    0x0F, 0x00,  // ....XXXX........
    0x3F, 0xC0,  // ..XXXXXXXX......
    0x7F, 0xE0,  // .XXXXXXXXXX.....
    0xFF, 0xF0,  // XXXXXXXXXXXX....
    0xFF, 0xF0,  // XXXXXXXXXXXX....
    0xFF, 0xF8,  // XXXXXXXXXXXXX...
    0xFF, 0xF8,  // XXXXXXXXXXXXX...
    0xFF, 0xF8,  // XXXXXXXXXXXXX...
    0xFF, 0xF8,  // XXXXXXXXXXXXX...
    0xFF, 0xF0,  // XXXXXXXXXXXX....
    0xFF, 0xF0,  // XXXXXXXXXXXX....
    0x7F, 0xE0,  // .XXXXXXXXXX.....
    0x3F, 0xC0,  // ..XXXXXXXX......
    0x0F, 0x00,  // ....XXXX........
    0x00, 0x00,  // ................
    0x00, 0x00,  // ................
};

// Help Cursor (16x16) - Arrow with question mark
static const uint8_t retro_help_image[] = {
    0x00, 0x00,  // ................
    0x40, 0x00,  // .X..............
    0x60, 0x00,  // .XX.............
    0x70, 0x00,  // .XXX............
    0x78, 0x00,  // .XXXX...........
    0x7C, 0x00,  // .XXXXX..........
    0x7E, 0x00,  // .XXXXXX.........
    0x7F, 0x00,  // .XXXXXXX........
    0x7C, 0xE0,  // .XXXXX..XXX.....
    0x6C, 0x90,  // .XX.XX..X..X....
    0x46, 0x10,  // .X...XX....X....
    0x06, 0x20,  // .....XX...X.....
    0x03, 0x40,  // ......XX.X......
    0x03, 0x00,  // ......XX........
    0x00, 0x40,  // .........X......
    0x00, 0x00,  // ................
};

static const uint8_t retro_help_mask[] = {
    0xC0, 0x00,  // XX..............
    0xE0, 0x00,  // XXX.............
    0xF0, 0x00,  // XXXX............
    0xF8, 0x00,  // XXXXX...........
    0xFC, 0x00,  // XXXXXX..........
    0xFE, 0x00,  // XXXXXXX.........
    0xFF, 0x00,  // XXXXXXXX........
    0xFF, 0xF0,  // XXXXXXXXXXXX....
    0xFF, 0xF8,  // XXXXXXXXXXXXX...
    0xFF, 0xF8,  // XXXXXXXXXXXXX...
    0xEF, 0xF8,  // XXX.XXXXXXXXX...
    0x4F, 0xF0,  // .X..XXXXXXXX....
    0x07, 0xE0,  // .....XXXXXX.....
    0x07, 0xE0,  // .....XXXXXX.....
    0x01, 0xE0,  // .......XXXX.....
    0x00, 0xE0,  // ........XXX.....
};

// ============================================================================
// Cursor Bitmap Definitions
// ============================================================================

static const cursor_bitmap_t retro_cursors[] = {
    [CURSOR_DEFAULT] = {
        .width = 16, .height = 16,
        .hotspot_x = 1, .hotspot_y = 1,
        .image = retro_arrow_image, .mask = retro_arrow_mask
    },
    [CURSOR_TEXT] = {
        .width = 16, .height = 16,
        .hotspot_x = 3, .hotspot_y = 7,
        .image = retro_ibeam_image, .mask = retro_ibeam_mask
    },
    [CURSOR_HAND] = {
        .width = 16, .height = 16,
        .hotspot_x = 5, .hotspot_y = 1,
        .image = retro_hand_image, .mask = retro_hand_mask
    },
    [CURSOR_WAIT] = {
        .width = 16, .height = 16,
        .hotspot_x = 7, .hotspot_y = 7,
        .image = retro_wait_image, .mask = retro_wait_mask
    },
    [CURSOR_RESIZE_NS] = {
        .width = 16, .height = 16,
        .hotspot_x = 6, .hotspot_y = 7,
        .image = retro_resize_ns_image, .mask = retro_resize_ns_mask
    },
    [CURSOR_RESIZE_EW] = {
        .width = 16, .height = 16,
        .hotspot_x = 7, .hotspot_y = 6,
        .image = retro_resize_ew_image, .mask = retro_resize_ew_mask
    },
    [CURSOR_RESIZE_NESW] = {
        .width = 16, .height = 16,
        .hotspot_x = 7, .hotspot_y = 7,
        .image = retro_resize_nesw_image, .mask = retro_resize_nesw_mask
    },
    [CURSOR_RESIZE_NWSE] = {
        .width = 16, .height = 16,
        .hotspot_x = 7, .hotspot_y = 7,
        .image = retro_resize_nwse_image, .mask = retro_resize_nwse_mask
    },
    [CURSOR_MOVE] = {
        .width = 16, .height = 16,
        .hotspot_x = 7, .hotspot_y = 7,
        .image = retro_move_image, .mask = retro_move_mask
    },
    [CURSOR_CROSSHAIR] = {
        .width = 16, .height = 16,
        .hotspot_x = 6, .hotspot_y = 7,
        .image = retro_crosshair_image, .mask = retro_crosshair_mask
    },
    [CURSOR_NOT_ALLOWED] = {
        .width = 16, .height = 16,
        .hotspot_x = 6, .hotspot_y = 6,
        .image = retro_forbidden_image, .mask = retro_forbidden_mask
    },
    [CURSOR_HELP] = {
        .width = 16, .height = 16,
        .hotspot_x = 1, .hotspot_y = 1,
        .image = retro_help_image, .mask = retro_help_mask
    },
    [CURSOR_PROGRESS] = {
        .width = 16, .height = 16,
        .hotspot_x = 1, .hotspot_y = 1,
        .image = retro_arrow_image, .mask = retro_arrow_mask  // Same as arrow for now
    },
};

// Static cursor definitions for retro theme
static const cursor_def_t retro_cursor_defs[] = {
    [CURSOR_DEFAULT] = { .type = CURSOR_DEFAULT, .animated = false, .data.static_image = &retro_cursors[CURSOR_DEFAULT] },
    [CURSOR_TEXT] = { .type = CURSOR_TEXT, .animated = false, .data.static_image = &retro_cursors[CURSOR_TEXT] },
    [CURSOR_HAND] = { .type = CURSOR_HAND, .animated = false, .data.static_image = &retro_cursors[CURSOR_HAND] },
    [CURSOR_WAIT] = { .type = CURSOR_WAIT, .animated = false, .data.static_image = &retro_cursors[CURSOR_WAIT] },
    [CURSOR_RESIZE_NS] = { .type = CURSOR_RESIZE_NS, .animated = false, .data.static_image = &retro_cursors[CURSOR_RESIZE_NS] },
    [CURSOR_RESIZE_EW] = { .type = CURSOR_RESIZE_EW, .animated = false, .data.static_image = &retro_cursors[CURSOR_RESIZE_EW] },
    [CURSOR_RESIZE_NESW] = { .type = CURSOR_RESIZE_NESW, .animated = false, .data.static_image = &retro_cursors[CURSOR_RESIZE_NESW] },
    [CURSOR_RESIZE_NWSE] = { .type = CURSOR_RESIZE_NWSE, .animated = false, .data.static_image = &retro_cursors[CURSOR_RESIZE_NWSE] },
    [CURSOR_MOVE] = { .type = CURSOR_MOVE, .animated = false, .data.static_image = &retro_cursors[CURSOR_MOVE] },
    [CURSOR_CROSSHAIR] = { .type = CURSOR_CROSSHAIR, .animated = false, .data.static_image = &retro_cursors[CURSOR_CROSSHAIR] },
    [CURSOR_NOT_ALLOWED] = { .type = CURSOR_NOT_ALLOWED, .animated = false, .data.static_image = &retro_cursors[CURSOR_NOT_ALLOWED] },
    [CURSOR_HELP] = { .type = CURSOR_HELP, .animated = false, .data.static_image = &retro_cursors[CURSOR_HELP] },
    [CURSOR_PROGRESS] = { .type = CURSOR_PROGRESS, .animated = false, .data.static_image = &retro_cursors[CURSOR_PROGRESS] },
};

// ============================================================================
// Global Cursor State
// ============================================================================

static cursor_state_t g_cursor_state;
static bool g_cursor_initialized = false;

// Cursor definition table [theme][type]
static const cursor_def_t *g_cursor_table[CURSOR_THEME_COUNT][CURSOR_COUNT];

// ============================================================================
// Cursor System Implementation
// ============================================================================

void cursor_init(void) {
    if (g_cursor_initialized) return;

    kprintf("[Cursor] Initializing cursor system...\n");

    // Initialize cursor state
    g_cursor_state.current_type = CURSOR_DEFAULT;
    g_cursor_state.current_theme = CURSOR_THEME_RETRO;
    g_cursor_state.x = 0;
    g_cursor_state.y = 0;
    g_cursor_state.visible = true;
    g_cursor_state.anim_frame = 0;
    g_cursor_state.anim_timer = 0;
    g_cursor_state.bg_saved = false;

    // Initialize cursor table with retro theme
    for (int type = 0; type < CURSOR_COUNT; type++) {
        g_cursor_table[CURSOR_THEME_RETRO][type] = &retro_cursor_defs[type];
        // Modern themes default to retro for now
        g_cursor_table[CURSOR_THEME_MODERN_LIGHT][type] = &retro_cursor_defs[type];
        g_cursor_table[CURSOR_THEME_MODERN_DARK][type] = &retro_cursor_defs[type];
    }

    g_cursor_initialized = true;
    kprintf("[Cursor] Cursor system initialized with %d cursor types\n", CURSOR_COUNT);
}

void cursor_set_theme(cursor_theme_t theme) {
    if (theme >= CURSOR_THEME_COUNT) return;
    g_cursor_state.current_theme = theme;
}

cursor_theme_t cursor_get_theme(void) {
    return g_cursor_state.current_theme;
}

void cursor_set_type(cursor_type_t type) {
    if (type >= CURSOR_COUNT) return;

    if (g_cursor_state.current_type != type) {
        g_cursor_state.current_type = type;
        g_cursor_state.anim_frame = 0;
        g_cursor_state.anim_timer = 0;
    }
}

cursor_type_t cursor_get_type(void) {
    return g_cursor_state.current_type;
}

void cursor_set_position(int32_t x, int32_t y) {
    // Clamp to screen bounds
    uint32_t screen_w = fb_get_width();
    uint32_t screen_h = fb_get_height();

    if (x < 0) x = 0;
    if (y < 0) y = 0;
    if ((uint32_t)x >= screen_w) x = screen_w - 1;
    if ((uint32_t)y >= screen_h) y = screen_h - 1;

    g_cursor_state.x = x;
    g_cursor_state.y = y;
}

void cursor_get_position(int32_t *x, int32_t *y) {
    if (x) *x = g_cursor_state.x;
    if (y) *y = g_cursor_state.y;
}

void cursor_show(void) {
    g_cursor_state.visible = true;
}

void cursor_hide(void) {
    g_cursor_state.visible = false;
}

bool cursor_is_visible(void) {
    return g_cursor_state.visible;
}

void cursor_restore_background(void) {
    if (!g_cursor_state.bg_saved) return;

    uint32_t screen_w = fb_get_width();
    uint32_t screen_h = fb_get_height();

    // Restore saved background
    for (int32_t py = 0; py < g_cursor_state.saved_height; py++) {
        for (int32_t px = 0; px < g_cursor_state.saved_width; px++) {
            int32_t sx = g_cursor_state.saved_x + px;
            int32_t sy = g_cursor_state.saved_y + py;
            if (sx >= 0 && sy >= 0 && (uint32_t)sx < screen_w && (uint32_t)sy < screen_h) {
                uint32_t color = g_cursor_state.saved_bg[py * CURSOR_MAX_WIDTH + px];
                fb_put_pixel(sx, sy, color);
            }
        }
    }

    g_cursor_state.bg_saved = false;
}

void cursor_draw(void) {
    if (!g_cursor_initialized || !g_cursor_state.visible) return;

    const cursor_def_t *def = g_cursor_table[g_cursor_state.current_theme][g_cursor_state.current_type];
    if (!def) return;

    const cursor_bitmap_t *bitmap;
    if (def->animated && def->data.animation.frames && def->data.animation.frame_count > 0) {
        bitmap = def->data.animation.frames[g_cursor_state.anim_frame].frame;
    } else {
        bitmap = def->data.static_image;
    }
    if (!bitmap) return;

    uint32_t screen_w = fb_get_width();
    uint32_t screen_h = fb_get_height();

    // Calculate cursor position (adjusted by hotspot)
    int32_t draw_x = g_cursor_state.x - bitmap->hotspot_x;
    int32_t draw_y = g_cursor_state.y - bitmap->hotspot_y;

    // Save background
    g_cursor_state.saved_x = draw_x;
    g_cursor_state.saved_y = draw_y;
    g_cursor_state.saved_width = bitmap->width;
    g_cursor_state.saved_height = bitmap->height;

    for (int32_t py = 0; py < bitmap->height; py++) {
        for (int32_t px = 0; px < bitmap->width; px++) {
            int32_t sx = draw_x + px;
            int32_t sy = draw_y + py;
            if (sx >= 0 && sy >= 0 && (uint32_t)sx < screen_w && (uint32_t)sy < screen_h) {
                g_cursor_state.saved_bg[py * CURSOR_MAX_WIDTH + px] = fb_get_pixel(sx, sy);
            }
        }
    }
    g_cursor_state.bg_saved = true;

    // Draw cursor
    uint32_t white = 0xFFFFFF;
    uint32_t black = 0x000000;

    for (int32_t py = 0; py < bitmap->height; py++) {
        // Get the byte index for this row (16-bit wide bitmap = 2 bytes per row)
        int byte_offset = py * 2;

        for (int32_t px = 0; px < bitmap->width; px++) {
            int32_t sx = draw_x + px;
            int32_t sy = draw_y + py;

            if (sx < 0 || sy < 0 || (uint32_t)sx >= screen_w || (uint32_t)sy >= screen_h)
                continue;

            // Get byte and bit for this pixel
            int bit_index = 7 - (px % 8);
            int byte_index = byte_offset + (px / 8);

            uint8_t mask_bit = (bitmap->mask[byte_index] >> bit_index) & 1;
            uint8_t image_bit = (bitmap->image[byte_index] >> bit_index) & 1;

            if (mask_bit) {
                // Pixel is visible
                if (image_bit) {
                    fb_put_pixel(sx, sy, white);
                } else {
                    fb_put_pixel(sx, sy, black);
                }
            }
        }
    }
}

void cursor_update(uint32_t delta_ms) {
    if (!g_cursor_initialized) return;

    const cursor_def_t *def = g_cursor_table[g_cursor_state.current_theme][g_cursor_state.current_type];
    if (!def || !def->animated) return;

    if (def->data.animation.frames && def->data.animation.frame_count > 1) {
        g_cursor_state.anim_timer += delta_ms;

        uint16_t frame_duration = def->data.animation.frames[g_cursor_state.anim_frame].duration_ms;
        if (g_cursor_state.anim_timer >= frame_duration) {
            g_cursor_state.anim_timer -= frame_duration;
            g_cursor_state.anim_frame++;
            if (g_cursor_state.anim_frame >= def->data.animation.frame_count) {
                g_cursor_state.anim_frame = 0;
            }
        }
    }
}

void cursor_get_hotspot(cursor_type_t type, int8_t *x, int8_t *y) {
    if (type >= CURSOR_COUNT) {
        if (x) *x = 0;
        if (y) *y = 0;
        return;
    }

    const cursor_def_t *def = g_cursor_table[g_cursor_state.current_theme][type];
    if (!def) {
        if (x) *x = 0;
        if (y) *y = 0;
        return;
    }

    const cursor_bitmap_t *bitmap = def->data.static_image;
    if (bitmap) {
        if (x) *x = bitmap->hotspot_x;
        if (y) *y = bitmap->hotspot_y;
    } else {
        if (x) *x = 0;
        if (y) *y = 0;
    }
}

void cursor_get_bounds(int32_t *x, int32_t *y, int32_t *w, int32_t *h) {
    const cursor_def_t *def = g_cursor_table[g_cursor_state.current_theme][g_cursor_state.current_type];
    const cursor_bitmap_t *bitmap = def ? def->data.static_image : NULL;

    if (bitmap) {
        if (x) *x = g_cursor_state.x - bitmap->hotspot_x;
        if (y) *y = g_cursor_state.y - bitmap->hotspot_y;
        if (w) *w = bitmap->width;
        if (h) *h = bitmap->height;
    } else {
        if (x) *x = g_cursor_state.x;
        if (y) *y = g_cursor_state.y;
        if (w) *w = 16;
        if (h) *h = 16;
    }
}

const cursor_def_t *cursor_get_def(cursor_type_t type, cursor_theme_t theme) {
    if (type >= CURSOR_COUNT || theme >= CURSOR_THEME_COUNT) {
        return NULL;
    }
    return g_cursor_table[theme][type];
}

int cursor_register(cursor_type_t type, cursor_theme_t theme, const cursor_def_t *def) {
    if (type >= CURSOR_COUNT || theme >= CURSOR_THEME_COUNT || !def) {
        return -1;
    }
    g_cursor_table[theme][type] = def;
    return 0;
}
