// font.c - Typography system implementation for MayteraOS GUI
#include "font.h"
#include "ttf.h"
#include "colors.h"
#include "../video/framebuffer.h"
#include "../serial.h"
#include "../string.h"
#include "../mm/heap.h"

// ============================================================================
// Built-in Font Data
// ============================================================================

// Import the system font glyph data from video/font.c
extern const uint8_t *font_get_glyph(char c);

// Small font (4x8) - Half-resolution version of system font
// Generated by sampling every other pixel from the 8x16 font
static const uint8_t small_font_data[128][8] = {
    // Basic ASCII characters (simplified bitmaps for 4x8 display)
    // Space through ~, control chars are blank
    [0 ... 31] = {0,0,0,0,0,0,0,0},
    [' '] = {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0},
    ['!'] = {0x4,0x4,0x4,0x4,0x4,0x0,0x4,0x0},
    ['"'] = {0xA,0xA,0x0,0x0,0x0,0x0,0x0,0x0},
    ['#'] = {0xA,0xF,0xA,0xA,0xF,0xA,0x0,0x0},
    ['$'] = {0x4,0xE,0x5,0xE,0xA,0xE,0x4,0x0},
    ['%'] = {0x9,0x2,0x4,0x8,0x9,0x0,0x0,0x0},
    ['&'] = {0x4,0xA,0x4,0xB,0xA,0xD,0x0,0x0},
    ['\''] = {0x4,0x4,0x0,0x0,0x0,0x0,0x0,0x0},
    ['('] = {0x2,0x4,0x4,0x4,0x4,0x4,0x2,0x0},
    [')'] = {0x4,0x2,0x2,0x2,0x2,0x2,0x4,0x0},
    ['*'] = {0x0,0xA,0x4,0xE,0x4,0xA,0x0,0x0},
    ['+'] = {0x0,0x4,0x4,0xE,0x4,0x4,0x0,0x0},
    [','] = {0x0,0x0,0x0,0x0,0x0,0x4,0x4,0x8},
    ['-'] = {0x0,0x0,0x0,0xE,0x0,0x0,0x0,0x0},
    ['.'] = {0x0,0x0,0x0,0x0,0x0,0x4,0x4,0x0},
    ['/'] = {0x1,0x2,0x2,0x4,0x4,0x8,0x8,0x0},
    ['0'] = {0x6,0x9,0x9,0x9,0x9,0x9,0x6,0x0},
    ['1'] = {0x4,0xC,0x4,0x4,0x4,0x4,0xE,0x0},
    ['2'] = {0x6,0x9,0x1,0x2,0x4,0x8,0xF,0x0},
    ['3'] = {0x6,0x9,0x1,0x6,0x1,0x9,0x6,0x0},
    ['4'] = {0x2,0x6,0xA,0xF,0x2,0x2,0x2,0x0},
    ['5'] = {0xF,0x8,0xE,0x1,0x1,0x9,0x6,0x0},
    ['6'] = {0x6,0x8,0xE,0x9,0x9,0x9,0x6,0x0},
    ['7'] = {0xF,0x1,0x2,0x4,0x4,0x4,0x4,0x0},
    ['8'] = {0x6,0x9,0x9,0x6,0x9,0x9,0x6,0x0},
    ['9'] = {0x6,0x9,0x9,0x7,0x1,0x1,0x6,0x0},
    [':'] = {0x0,0x0,0x4,0x0,0x0,0x4,0x0,0x0},
    [';'] = {0x0,0x0,0x4,0x0,0x0,0x4,0x4,0x8},
    ['<'] = {0x1,0x2,0x4,0x8,0x4,0x2,0x1,0x0},
    ['='] = {0x0,0x0,0xE,0x0,0xE,0x0,0x0,0x0},
    ['>'] = {0x8,0x4,0x2,0x1,0x2,0x4,0x8,0x0},
    ['?'] = {0x6,0x9,0x1,0x2,0x4,0x0,0x4,0x0},
    ['@'] = {0x6,0x9,0xB,0xB,0xA,0x8,0x6,0x0},
    ['A'] = {0x6,0x9,0x9,0xF,0x9,0x9,0x9,0x0},
    ['B'] = {0xE,0x9,0x9,0xE,0x9,0x9,0xE,0x0},
    ['C'] = {0x6,0x9,0x8,0x8,0x8,0x9,0x6,0x0},
    ['D'] = {0xE,0x9,0x9,0x9,0x9,0x9,0xE,0x0},
    ['E'] = {0xF,0x8,0x8,0xE,0x8,0x8,0xF,0x0},
    ['F'] = {0xF,0x8,0x8,0xE,0x8,0x8,0x8,0x0},
    ['G'] = {0x6,0x9,0x8,0xB,0x9,0x9,0x6,0x0},
    ['H'] = {0x9,0x9,0x9,0xF,0x9,0x9,0x9,0x0},
    ['I'] = {0xE,0x4,0x4,0x4,0x4,0x4,0xE,0x0},
    ['J'] = {0x7,0x2,0x2,0x2,0x2,0xA,0x4,0x0},
    ['K'] = {0x9,0xA,0xC,0x8,0xC,0xA,0x9,0x0},
    ['L'] = {0x8,0x8,0x8,0x8,0x8,0x8,0xF,0x0},
    ['M'] = {0x9,0xF,0xF,0x9,0x9,0x9,0x9,0x0},
    ['N'] = {0x9,0xD,0xF,0xB,0x9,0x9,0x9,0x0},
    ['O'] = {0x6,0x9,0x9,0x9,0x9,0x9,0x6,0x0},
    ['P'] = {0xE,0x9,0x9,0xE,0x8,0x8,0x8,0x0},
    ['Q'] = {0x6,0x9,0x9,0x9,0xB,0xA,0x5,0x0},
    ['R'] = {0xE,0x9,0x9,0xE,0xA,0x9,0x9,0x0},
    ['S'] = {0x6,0x9,0x8,0x6,0x1,0x9,0x6,0x0},
    ['T'] = {0xF,0x4,0x4,0x4,0x4,0x4,0x4,0x0},
    ['U'] = {0x9,0x9,0x9,0x9,0x9,0x9,0x6,0x0},
    ['V'] = {0x9,0x9,0x9,0x9,0x9,0x6,0x6,0x0},
    ['W'] = {0x9,0x9,0x9,0x9,0xF,0xF,0x9,0x0},
    ['X'] = {0x9,0x9,0x6,0x6,0x6,0x9,0x9,0x0},
    ['Y'] = {0x9,0x9,0x9,0x6,0x4,0x4,0x4,0x0},
    ['Z'] = {0xF,0x1,0x2,0x4,0x8,0x8,0xF,0x0},
    ['['] = {0x6,0x4,0x4,0x4,0x4,0x4,0x6,0x0},
    ['\\'] = {0x8,0x8,0x4,0x4,0x2,0x2,0x1,0x0},
    [']'] = {0x6,0x2,0x2,0x2,0x2,0x2,0x6,0x0},
    ['^'] = {0x4,0xA,0x0,0x0,0x0,0x0,0x0,0x0},
    ['_'] = {0x0,0x0,0x0,0x0,0x0,0x0,0xF,0x0},
    ['`'] = {0x4,0x2,0x0,0x0,0x0,0x0,0x0,0x0},
    ['a'] = {0x0,0x0,0x6,0x1,0x7,0x9,0x7,0x0},
    ['b'] = {0x8,0x8,0xE,0x9,0x9,0x9,0xE,0x0},
    ['c'] = {0x0,0x0,0x6,0x9,0x8,0x9,0x6,0x0},
    ['d'] = {0x1,0x1,0x7,0x9,0x9,0x9,0x7,0x0},
    ['e'] = {0x0,0x0,0x6,0x9,0xF,0x8,0x6,0x0},
    ['f'] = {0x2,0x5,0x4,0xE,0x4,0x4,0x4,0x0},
    ['g'] = {0x0,0x0,0x7,0x9,0x9,0x7,0x1,0x6},
    ['h'] = {0x8,0x8,0xE,0x9,0x9,0x9,0x9,0x0},
    ['i'] = {0x4,0x0,0xC,0x4,0x4,0x4,0xE,0x0},
    ['j'] = {0x2,0x0,0x6,0x2,0x2,0x2,0xA,0x4},
    ['k'] = {0x8,0x8,0x9,0xA,0xC,0xA,0x9,0x0},
    ['l'] = {0xC,0x4,0x4,0x4,0x4,0x4,0xE,0x0},
    ['m'] = {0x0,0x0,0xA,0xF,0x9,0x9,0x9,0x0},
    ['n'] = {0x0,0x0,0xE,0x9,0x9,0x9,0x9,0x0},
    ['o'] = {0x0,0x0,0x6,0x9,0x9,0x9,0x6,0x0},
    ['p'] = {0x0,0x0,0xE,0x9,0x9,0xE,0x8,0x8},
    ['q'] = {0x0,0x0,0x7,0x9,0x9,0x7,0x1,0x1},
    ['r'] = {0x0,0x0,0xB,0xC,0x8,0x8,0x8,0x0},
    ['s'] = {0x0,0x0,0x6,0x8,0x6,0x1,0xE,0x0},
    ['t'] = {0x4,0x4,0xE,0x4,0x4,0x5,0x2,0x0},
    ['u'] = {0x0,0x0,0x9,0x9,0x9,0x9,0x6,0x0},
    ['v'] = {0x0,0x0,0x9,0x9,0x9,0x6,0x6,0x0},
    ['w'] = {0x0,0x0,0x9,0x9,0x9,0xF,0x6,0x0},
    ['x'] = {0x0,0x0,0x9,0x6,0x6,0x6,0x9,0x0},
    ['y'] = {0x0,0x0,0x9,0x9,0x9,0x7,0x1,0x6},
    ['z'] = {0x0,0x0,0xF,0x2,0x4,0x8,0xF,0x0},
    ['{'] = {0x2,0x4,0x4,0x8,0x4,0x4,0x2,0x0},
    ['|'] = {0x4,0x4,0x4,0x4,0x4,0x4,0x4,0x0},
    ['}'] = {0x4,0x2,0x2,0x1,0x2,0x2,0x4,0x0},
    ['~'] = {0x0,0x5,0xA,0x0,0x0,0x0,0x0,0x0},
    [0x7F] = {0xF,0xF,0xF,0xF,0xF,0xF,0xF,0xF},
};

// ============================================================================
// Font Definitions
// ============================================================================

// System font (8x16) - uses video/font.c data
static font_t system_font = {
    .name = "System",
    .metrics = {
        .width = 8,
        .height = 16,
        .baseline = 12,
        .line_height = 18,
        .ascent = 12,
        .descent = 4,
        .char_spacing = 0,
    },
    .render_mode = FONT_RENDER_BITMAP,
    .glyph_data = NULL,  // Uses font_get_glyph()
    .first_char = 0,
    .last_char = 127,
    .glyph_size = 16,
    .is_loaded = false,
};

// Title font (8x16, bold effect) - same size but rendered with emphasis
static font_t title_font = {
    .name = "Title",
    .metrics = {
        .width = 8,
        .height = 16,
        .baseline = 12,
        .line_height = 18,
        .ascent = 12,
        .descent = 4,
        .char_spacing = 1,  // Slightly wider spacing
    },
    .render_mode = FONT_RENDER_BITMAP,
    .glyph_data = NULL,  // Uses font_get_glyph() with bold effect
    .first_char = 0,
    .last_char = 127,
    .glyph_size = 16,
    .is_loaded = false,
};

// Monospace font (8x16) - same as system for now
static font_t mono_font = {
    .name = "Mono",
    .metrics = {
        .width = 8,
        .height = 16,
        .baseline = 12,
        .line_height = 18,
        .ascent = 12,
        .descent = 4,
        .char_spacing = 0,
    },
    .render_mode = FONT_RENDER_BITMAP,
    .glyph_data = NULL,
    .first_char = 0,
    .last_char = 127,
    .glyph_size = 16,
    .is_loaded = false,
};

// Small font (4x8)
static font_t small_font = {
    .name = "Small",
    .metrics = {
        .width = 4,
        .height = 8,
        .baseline = 6,
        .line_height = 10,
        .ascent = 6,
        .descent = 2,
        .char_spacing = 0,
    },
    .render_mode = FONT_RENDER_BITMAP,
    .glyph_data = (const uint8_t *)small_font_data,
    .first_char = 0,
    .last_char = 127,
    .glyph_size = 8,
    .is_loaded = false,
};

// Icon font placeholder
static font_t icon_font = {
    .name = "Icons",
    .metrics = {
        .width = 16,
        .height = 16,
        .baseline = 14,
        .line_height = 18,
        .ascent = 14,
        .descent = 2,
        .char_spacing = 2,
    },
    .render_mode = FONT_RENDER_BITMAP,
    .glyph_data = NULL,
    .first_char = 0,
    .last_char = 127,
    .glyph_size = 32,
    .is_loaded = false,
};

// Font table
static font_t *fonts[FONT_COUNT] = {
    &system_font,
    &title_font,
    &mono_font,
    &small_font,
    &icon_font,
};

// Current rendering mode
static font_render_mode_t g_render_mode = FONT_RENDER_BITMAP;

// ============================================================================
// Font System Initialization
// ============================================================================

void font_system_init(void) {
    kprintf("[Typography] Font system initializing...\n");

    // Initialize font pointers
    fonts[FONT_SYSTEM] = &system_font;
    fonts[FONT_TITLE] = &title_font;
    fonts[FONT_MONO] = &mono_font;
    fonts[FONT_SMALL] = &small_font;
    fonts[FONT_ICON] = &icon_font;

    kprintf("[Typography] Registered %d fonts:\n", FONT_COUNT);
    for (int i = 0; i < FONT_COUNT; i++) {
        kprintf("  [%d] %s: %dx%d\n", i, fonts[i]->name,
                fonts[i]->metrics.width, fonts[i]->metrics.height);
    }

    kprintf("[Typography] Font system initialized\n");
}

// ============================================================================
// Font Access Functions
// ============================================================================

const font_t *font_get(font_id_t font_id) {
    if (font_id >= FONT_COUNT) {
        return fonts[FONT_SYSTEM];  // Fallback to system font
    }
    return fonts[font_id];
}

const font_metrics_t *font_get_metrics(font_id_t font_id) {
    const font_t *font = font_get(font_id);
    return &font->metrics;
}

const uint8_t *font_get_char_glyph(font_id_t font_id, char c) {
    const font_t *font = font_get(font_id);
    unsigned char uc = (unsigned char)c;

    if (uc < font->first_char || uc > font->last_char) {
        return NULL;
    }

    // For system, title, and mono fonts, use the video/font.c data
    if (font_id == FONT_SYSTEM || font_id == FONT_TITLE || font_id == FONT_MONO) {
        return font_get_glyph(c);
    }

    // For small font, use built-in data
    if (font_id == FONT_SMALL && font->glyph_data) {
        return &((const uint8_t *)small_font_data)[uc * 8];
    }

    // For loaded fonts, calculate offset
    if (font->glyph_data && font->is_loaded) {
        uint32_t index = uc - font->first_char;
        return &font->glyph_data[index * font->glyph_size];
    }

    return NULL;
}

// ============================================================================
// Text Measurement
// ============================================================================

int32_t font_measure_string(font_id_t font_id, const char *str) {
    if (!str) return 0;
    // Use TTF measurement when available (except for FONT_ICON)
    if (ttf_is_ready() && font_id != FONT_ICON) {
        int ttf_size = TTF_SIZE_NORMAL;
        if (font_id == FONT_SMALL) ttf_size = TTF_SIZE_SMALL;
        return ttf_measure_string(str, ttf_size);
    }

    const font_t *font = font_get(font_id);
    int32_t width = 0;
    int char_count = 0;

    while (*str) {
        width += font->metrics.width;
        if (char_count > 0) {
            width += font->metrics.char_spacing;
        }
        char_count++;
        str++;
    }

    return width;
}

int32_t font_measure_string_n(font_id_t font_id, const char *str, int max_chars) {
    if (!str || max_chars <= 0) return 0;

    const font_t *font = font_get(font_id);
    int32_t width = 0;
    int char_count = 0;

    while (*str && char_count < max_chars) {
        width += font->metrics.width;
        if (char_count > 0) {
            width += font->metrics.char_spacing;
        }
        char_count++;
        str++;
    }

    return width;
}

int32_t font_measure_wrapped_height(font_id_t font_id, const char *str, int32_t max_width) {
    if (!str || max_width <= 0) return 0;

    const font_t *font = font_get(font_id);
    int32_t line_count = 1;
    int32_t current_width = 0;

    while (*str) {
        if (*str == '\n') {
            line_count++;
            current_width = 0;
        } else {
            current_width += font->metrics.width + font->metrics.char_spacing;
            if (current_width > max_width) {
                line_count++;
                current_width = font->metrics.width;
            }
        }
        str++;
    }

    return line_count * font->metrics.line_height;
}

int font_chars_that_fit(font_id_t font_id, const char *str, int32_t max_width) {
    if (!str || max_width <= 0) return 0;

    const font_t *font = font_get(font_id);
    int count = 0;
    int32_t width = 0;

    while (*str) {
        int32_t char_width = font->metrics.width;
        if (count > 0) {
            char_width += font->metrics.char_spacing;
        }

        if (width + char_width > max_width) {
            break;
        }

        width += char_width;
        count++;
        str++;
    }

    return count;
}

// ============================================================================
// Basic Character Drawing
// ============================================================================

void font_draw_char(int32_t x, int32_t y, char c, font_id_t font_id, uint32_t color) {
    // Use TTF rendering when available (except for FONT_ICON)
    if (ttf_is_ready() && font_id != FONT_ICON) {
        int ttf_size = TTF_SIZE_NORMAL;
        int ttf_style = TTF_STYLE_NORMAL;
        if (font_id == FONT_SMALL) ttf_size = TTF_SIZE_SMALL;
        else if (font_id == FONT_TITLE) ttf_style = TTF_STYLE_BOLD;
        ttf_draw_char(x, y, (unsigned char)c, ttf_size, ttf_style, color);
        return;
    }
    const font_t *font = font_get(font_id);
    const uint8_t *glyph = font_get_char_glyph(font_id, c);

    if (!glyph) return;

    // Draw small font (4-bit wide glyphs)
    if (font_id == FONT_SMALL) {
        for (int row = 0; row < font->metrics.height; row++) {
            uint8_t bits = glyph[row];
            for (int col = 0; col < font->metrics.width; col++) {
                if (bits & (0x8 >> col)) {
                    fb_put_pixel(x + col, y + row, color);
                }
            }
        }
        return;
    }

    // Draw standard fonts (8-bit wide glyphs)
    for (int row = 0; row < font->metrics.height; row++) {
        uint8_t bits = glyph[row];
        for (int col = 0; col < font->metrics.width; col++) {
            if (bits & (0x80 >> col)) {
                fb_put_pixel(x + col, y + row, color);

                // Bold effect for title font - draw pixel twice
                if (font_id == FONT_TITLE && col > 0) {
                    fb_put_pixel(x + col + 1, y + row, color);
                }
            }
        }
    }
}

void font_draw_char_bg(int32_t x, int32_t y, char c, font_id_t font_id,
                       uint32_t fg_color, uint32_t bg_color) {
    const font_t *font = font_get(font_id);
    const uint8_t *glyph = font_get_char_glyph(font_id, c);

    if (!glyph) {
        // Draw background only for missing glyphs
        fb_fill_rect(x, y, font->metrics.width, font->metrics.height, bg_color);
        return;
    }

    // Draw small font
    if (font_id == FONT_SMALL) {
        for (int row = 0; row < font->metrics.height; row++) {
            uint8_t bits = glyph[row];
            for (int col = 0; col < font->metrics.width; col++) {
                uint32_t color = (bits & (0x8 >> col)) ? fg_color : bg_color;
                fb_put_pixel(x + col, y + row, color);
            }
        }
        return;
    }

    // Draw standard fonts
    for (int row = 0; row < font->metrics.height; row++) {
        uint8_t bits = glyph[row];
        for (int col = 0; col < font->metrics.width; col++) {
            uint32_t color = (bits & (0x80 >> col)) ? fg_color : bg_color;
            fb_put_pixel(x + col, y + row, color);
        }
    }
}

// ============================================================================
// String Drawing
// ============================================================================

void font_draw_string(int32_t x, int32_t y, const char *str,
                      font_id_t font_id, uint32_t color) {
    if (!str) return;
    // Use TTF rendering when available (except for FONT_ICON)
    if (ttf_is_ready() && font_id != FONT_ICON) {
        int ttf_size = TTF_SIZE_NORMAL;
        if (font_id == FONT_SMALL) ttf_size = TTF_SIZE_SMALL;
        ttf_draw_string(x, y, str, ttf_size, color);
        return;
    }

    const font_t *font = font_get(font_id);
    int32_t start_x = x;

    while (*str) {
        if (*str == '\n') {
            x = start_x;
            y += font->metrics.line_height;
        } else if (*str == '\t') {
            // Tab to next 4-character boundary
            int tab_width = 4 * (font->metrics.width + font->metrics.char_spacing);
            x = ((x - start_x + tab_width) / tab_width) * tab_width + start_x;
        } else {
            font_draw_char(x, y, *str, font_id, color);
            x += font->metrics.width + font->metrics.char_spacing;
        }
        str++;
    }
}

void font_draw_string_bg(int32_t x, int32_t y, const char *str,
                         font_id_t font_id, uint32_t fg_color, uint32_t bg_color) {
    if (!str) return;
    // Use TTF rendering when available (except for FONT_ICON)
    if (ttf_is_ready() && font_id != FONT_ICON) {
        int ttf_size = TTF_SIZE_NORMAL;
        if (font_id == FONT_SMALL) ttf_size = TTF_SIZE_SMALL;
        // Fill background, then render TTF text
        int w = ttf_measure_string(str, ttf_size);
        fb_fill_rect(x, y, w, ttf_size + 4, bg_color);
        ttf_draw_string(x, y, str, ttf_size, fg_color);
        return;
    }

    const font_t *font = font_get(font_id);
    int32_t start_x = x;

    while (*str) {
        if (*str == '\n') {
            x = start_x;
            y += font->metrics.line_height;
        } else if (*str == '\t') {
            int tab_width = 4 * (font->metrics.width + font->metrics.char_spacing);
            int32_t next_x = ((x - start_x + tab_width) / tab_width) * tab_width + start_x;
            fb_fill_rect(x, y, next_x - x, font->metrics.height, bg_color);
            x = next_x;
        } else {
            font_draw_char_bg(x, y, *str, font_id, fg_color, bg_color);
            x += font->metrics.width + font->metrics.char_spacing;
        }
        str++;
    }
}

// ============================================================================
// Advanced Text Drawing
// ============================================================================

void font_draw_text(int32_t x, int32_t y, const char *str, const text_options_t *options) {
    if (!str || !options) return;
    // Use TTF rendering when available (except for FONT_ICON)
    if (ttf_is_ready() && options->font != FONT_ICON) {
        int ttf_size = TTF_SIZE_NORMAL;
        if (options->font == FONT_SMALL) ttf_size = TTF_SIZE_SMALL;
        // Draw shadow if configured
        if (options->shadow_offset_x != 0 || options->shadow_offset_y != 0) {
            ttf_draw_string(x + options->shadow_offset_x, y + options->shadow_offset_y,
                           str, ttf_size, options->shadow_color);
        }
        ttf_draw_string(x, y, str, ttf_size, options->color);
        // Underline if styled
        if (options->style & FONT_STYLE_UNDERLINE) {
            int32_t width = ttf_measure_string(str, ttf_size);
            fb_draw_line(x, y + ttf_size, x + width - 1, y + ttf_size, options->color);
        }
        return;
    }

    // Draw shadow first if specified
    if (options->shadow_offset_x != 0 || options->shadow_offset_y != 0) {
        if (options->bg_color != 0) {
            font_draw_string_bg(x + options->shadow_offset_x,
                               y + options->shadow_offset_y,
                               str, options->font,
                               options->shadow_color, options->bg_color);
        } else {
            font_draw_string(x + options->shadow_offset_x,
                            y + options->shadow_offset_y,
                            str, options->font, options->shadow_color);
        }
    }

    // Draw main text
    if (options->bg_color != 0) {
        font_draw_string_bg(x, y, str, options->font, options->color, options->bg_color);
    } else {
        font_draw_string(x, y, str, options->font, options->color);
    }

    // Draw underline if specified
    if (options->style & FONT_STYLE_UNDERLINE) {
        const font_t *font = font_get(options->font);
        int32_t width = font_measure_string(options->font, str);
        int32_t underline_y = y + font->metrics.baseline + 2;
        fb_draw_line(x, underline_y, x + width - 1, underline_y, options->color);
    }
}

void font_draw_text_box(int32_t x, int32_t y, int32_t width, int32_t height,
                        const char *str, const text_options_t *options) {
    if (!str || !options || width <= 0 || height <= 0) return;

    const font_t *font = font_get(options->font);
    int32_t text_width = font_measure_string(options->font, str);
    int32_t text_height = font->metrics.height;

    // Truncate with ellipsis if needed
    char truncated[256];
    const char *draw_str = str;

    if (options->ellipsis && text_width > width) {
        int chars_fit = font_chars_that_fit(options->font, str, width - font->metrics.width * 3);
        if (chars_fit > 0) {
            strncpy(truncated, str, chars_fit);
            truncated[chars_fit] = '\0';
            strcat(truncated, "...");
            draw_str = truncated;
            text_width = font_measure_string(options->font, draw_str);
        }
    }

    // Calculate position based on alignment
    int32_t draw_x = x;
    int32_t draw_y = y;

    switch (options->align) {
        case TEXT_ALIGN_CENTER:
            draw_x = x + (width - text_width) / 2;
            break;
        case TEXT_ALIGN_RIGHT:
            draw_x = x + width - text_width;
            break;
        default:
            break;
    }

    switch (options->valign) {
        case TEXT_VALIGN_MIDDLE:
            draw_y = y + (height - text_height) / 2;
            break;
        case TEXT_VALIGN_BOTTOM:
            draw_y = y + height - text_height;
            break;
        default:
            break;
    }

    // Create modified options for actual drawing
    text_options_t draw_options = *options;
    font_draw_text(draw_x, draw_y, draw_str, &draw_options);
}

void font_draw_text_wrapped(int32_t x, int32_t y, int32_t max_width,
                            const char *str, font_id_t font_id, uint32_t color) {
    if (!str || max_width <= 0) return;

    const font_t *font = font_get(font_id);
    int32_t start_x = x;
    int32_t current_x = x;
    int32_t current_y = y;

    const char *ptr = str;
    const char *word_start __attribute__((unused)) = str;

    while (*ptr) {
        // Handle explicit newlines
        if (*ptr == '\n') {
            current_x = start_x;
            current_y += font->metrics.line_height;
            ptr++;
            word_start = ptr;
            continue;
        }

        // Find end of current word
        const char *word_end = ptr;
        while (*word_end && *word_end != ' ' && *word_end != '\n') {
            word_end++;
        }

        // Measure the word
        int word_len = word_end - ptr;
        int32_t word_width = font_measure_string_n(font_id, ptr, word_len);

        // Check if word fits on current line
        if (current_x != start_x && current_x + word_width > start_x + max_width) {
            // Wrap to next line
            current_x = start_x;
            current_y += font->metrics.line_height;
        }

        // Draw the word
        for (int i = 0; i < word_len; i++) {
            font_draw_char(current_x, current_y, ptr[i], font_id, color);
            current_x += font->metrics.width + font->metrics.char_spacing;
        }

        ptr = word_end;

        // Handle space after word
        if (*ptr == ' ') {
            current_x += font->metrics.width;
            ptr++;
        }

        word_start = ptr;
    }
}

// ============================================================================
// Styled Text Drawing
// ============================================================================

void font_draw_styled_text(int32_t x, int32_t y, const char *str,
                           font_id_t base_font, uint32_t default_color) {
    if (!str) return;

    const font_t *font = font_get(base_font);
    uint32_t current_color = default_color;
    uint8_t current_style = FONT_STYLE_NORMAL;

    while (*str) {
        // Check for style codes
        if (*str == '^' && *(str + 1)) {
            char code = *(str + 1);

            switch (code) {
                case 'B':  // Toggle bold
                    current_style ^= FONT_STYLE_BOLD;
                    str += 2;
                    continue;

                case 'I':  // Toggle italic (rendered as offset)
                    current_style ^= FONT_STYLE_ITALIC;
                    str += 2;
                    continue;

                case 'U':  // Toggle underline
                    current_style ^= FONT_STYLE_UNDERLINE;
                    str += 2;
                    continue;

                case 'R':  // Reset
                    current_color = default_color;
                    current_style = FONT_STYLE_NORMAL;
                    str += 2;
                    continue;

                case 'C':  // Set color (^Cxxxxxx)
                    if (strlen(str) >= 8) {
                        // Parse 6 hex digits
                        uint32_t color = 0;
                        for (int i = 0; i < 6; i++) {
                            char c = str[2 + i];
                            color <<= 4;
                            if (c >= '0' && c <= '9') color |= (c - '0');
                            else if (c >= 'A' && c <= 'F') color |= (c - 'A' + 10);
                            else if (c >= 'a' && c <= 'f') color |= (c - 'a' + 10);
                        }
                        current_color = color;
                        str += 8;
                        continue;
                    }
                    break;

                case '^':  // Escape ^
                    str++;
                    break;
            }
        }

        // Handle newline
        if (*str == '\n') {
            x = 0;  // Reset to start (caller should track start position)
            y += font->metrics.line_height;
            str++;
            continue;
        }

        // Draw character with current style
        int32_t draw_x = x;
        if (current_style & FONT_STYLE_ITALIC) {
            draw_x += 1;  // Simple italic effect
        }

        font_draw_char(draw_x, y, *str, base_font, current_color);

        // Bold effect - draw again offset by 1
        if (current_style & FONT_STYLE_BOLD) {
            font_draw_char(draw_x + 1, y, *str, base_font, current_color);
        }

        // Underline
        if (current_style & FONT_STYLE_UNDERLINE) {
            int32_t underline_y = y + font->metrics.baseline + 2;
            fb_draw_line(x, underline_y, x + font->metrics.width - 1, underline_y, current_color);
        }

        x += font->metrics.width + font->metrics.char_spacing;
        str++;
    }
}

// ============================================================================
// Font Loading
// ============================================================================

bool font_load_from_file(font_id_t slot, const char *path) {
    if (slot >= FONT_COUNT || !path) {
        kprintf("[Typography] Invalid font load parameters\n");
        return false;
    }

    // TODO: Implement file-based font loading
    // This would read from the filesystem (/FONTS/*.fnt)
    // For now, just log and return false

    kprintf("[Typography] Font loading from '%s' not yet implemented\n", path);
    return false;
}

void font_unload(font_id_t slot) {
    if (slot >= FONT_COUNT) return;

    font_t *font = fonts[slot];

    if (font->is_loaded && font->glyph_data) {
        // Free dynamically allocated glyph data
        kfree((void *)font->glyph_data);
        font->glyph_data = NULL;
        font->is_loaded = false;
    }

    // Reset to default built-in font
    switch (slot) {
        case FONT_SYSTEM:
            *font = system_font;
            break;
        case FONT_TITLE:
            *font = title_font;
            break;
        case FONT_MONO:
            *font = mono_font;
            break;
        case FONT_SMALL:
            *font = small_font;
            break;
        case FONT_ICON:
            *font = icon_font;
            break;
        default:
            break;
    }
}

// ============================================================================
// Theme Integration
// ============================================================================

void font_set_render_mode(font_render_mode_t mode) {
    g_render_mode = mode;

    // Update all fonts' render mode
    for (int i = 0; i < FONT_COUNT; i++) {
        fonts[i]->render_mode = mode;
    }

    kprintf("[Typography] Render mode set to %s\n",
            mode == FONT_RENDER_BITMAP ? "bitmap" : "antialiased");
}

font_render_mode_t font_get_render_mode(void) {
    return g_render_mode;
}
