/* bsdgame_words.c - OUR FILE, not upstream.
 *
 * A small built-in word list for hangman's getword.c (see patch
 * 0002-getword-builtin-wordlist.patch), replacing upstream's on-disk
 * dictionary lookup. Plain common English vocabulary written for this
 * port; a list of ordinary words carries no copyright, unlike a curated
 * dictionary file, so this avoids both a runtime data dependency and any
 * licence question a vendored /usr/share/dict/words would raise.
 */

const char *const bsdgame_words[] = {
	"about", "above", "abroad", "absence", "accept", "account", "acid",
	"across", "action", "active", "actor", "address", "advice", "afraid",
	"after", "again", "agent", "agree", "airport", "alarm", "album",
	"alive", "almost", "alone", "along", "already", "always", "amazing",
	"among", "amount", "ancient", "anger", "animal", "announce", "annual",
	"answer", "anxious", "anyone", "anything", "apart", "apple", "apply",
	"approach", "april", "arch", "argue", "arise", "around", "arrange",
	"arrival", "arrive", "article", "artist", "aside", "asleep", "aspect",
	"assist", "assume", "attack", "attempt", "attend", "attitude",
	"august", "author", "autumn", "average", "avoid", "awake", "aware",
	"balance", "balloon", "banana", "basket", "battle", "beach", "beauty",
	"become", "before", "begin", "behave", "behind", "believe", "belong",
	"below", "bench", "beside", "better", "between", "beyond", "bicycle",
	"birthday", "blanket", "border", "borrow", "bottle", "bottom",
	"bounce", "bracket", "branch", "bright", "bring", "broken", "brother",
	"brown", "budget", "burden", "camera", "campus", "cancel", "candle",
	"canyon", "capable", "capital", "carbon", "career", "careful",
	"carpet", "carry", "castle", "casual", "cattle", "ceiling",
	"central", "century", "certain", "chance", "change", "channel",
	"chapter", "charge", "chase", "cheerful", "cheese", "chicken",
	"choice", "choose", "circle", "citizen", "clever", "climate", "climb",
	"clinic", "closet", "cloud", "cluster", "coffee", "collect", "college",
	"combine", "comfort", "command", "comment", "common", "compare",
	"compete", "complex", "concern", "concert", "conduct", "confirm",
	"connect", "consider", "consist", "contact", "contain", "content",
	"contest", "context", "control", "convert", "cookie", "corner",
	"correct", "cottage", "council", "counter", "country", "couple",
	"courage", "course", "cousin", "cover", "create", "credit", "crystal",
	"culture", "curious", "current", "curtain", "custom", "damage",
	"dancer", "danger", "daughter", "decide", "declare", "decrease",
	"defend", "define", "degree", "delay", "deliver", "demand", "depend",
	"deposit", "depth", "describe", "desert", "design", "desire",
	"detail", "detect", "develop", "device", "diamond", "differ",
	"digital", "dinner", "direct", "discuss", "disease", "dismiss",
	"display", "distant", "district", "divide", "doctor", "document",
	"double", "dragon", "drawer", "dream", "driver", "during", "eager",
	"early", "earth", "easily", "eastern", "economy", "editor", "effect",
	"effort", "either", "elderly", "electric", "element", "elephant",
	"emerge", "emotion", "employ", "empty", "enable", "enemy", "energy",
	"engage", "engine", "enjoy", "enough", "ensure", "enter", "entire",
	"entry", "equal", "escape", "essay", "estate", "ethnic", "evening",
	"event", "eventual", "everyone", "exact", "example", "excess",
	"exchange", "excite", "exclude", "excuse", "exercise", "exhibit",
	"exist", "expand", "expect", "expense", "explain", "explore",
	"export", "expose", "extend", "extent", "extra", "fabric", "factor",
	"faculty", "family", "famous", "farmer", "fashion", "father",
	"feature", "federal", "fellow", "female", "fiction", "figure",
	"finance", "finger", "finish", "flavor", "flight", "flower", "follow",
	"forest", "forget", "formal", "format", "former", "fortune", "forward",
	"foster", "fought", "found", "fourth", "fragile", "friend", "frozen",
	"future", "galaxy", "gallery", "garage", "garden", "gather", "gender",
	"general", "gentle", "genuine", "gesture", "global", "golden",
	"government", "gradual", "grocery", "ground", "growth", "guard",
	"guess", "guide", "habit", "handle", "happen", "harbor", "harvest",
	"header", "health", "heavy", "helmet", "hidden", "history", "honest",
	"honey", "horizon", "hospital", "hunger", "hunter", "ideal",
	"identify", "image", "imagine", "impact", "import", "improve",
	"income", "increase", "indeed", "indoor", "initial", "injury",
	"inquiry", "insect", "insert", "inside", "inspect", "install",
	"instead", "insurance", "intend", "invite", "island", "issue",
	"jacket", "jewelry", "journal", "journey", "junior", "justice",
	"kingdom", "kitchen", "knight", "labor", "ladder", "language",
	"laptop", "latter", "launch", "lawyer", "leader", "league", "leather",
	"legend", "lemon", "length", "lesson", "letter", "liberty", "library",
	"license", "lively", "living", "logic", "lonely", "luggage",
	"machine", "magnet", "manage", "manner", "manual", "marble", "margin",
	"marine", "market", "marriage", "master", "match", "material",
	"matter", "maximum", "measure", "medical", "medium", "member",
	"memory", "mental", "mention", "merely", "method", "middle",
	"mineral", "minimum", "minute", "mirror", "mission", "mistake",
	"mixture", "mobile", "modern", "moment", "morning", "mostly",
	"mountain", "mouse", "muscle", "museum", "mutual", "nation",
	"native", "nature", "nearby", "nearly", "neither", "nephew",
	"network", "neutral", "normal", "notice", "novel", "nuclear",
	"number", "object", "obtain", "occupy", "occur", "office", "onion",
	"opening", "operate", "opinion", "orange", "orbit", "organize",
	"origin", "outcome", "output", "outside", "oxygen", "packet",
	"palace", "parent", "partner", "passage", "passenger", "patient",
	"pattern", "pause", "peace", "pencil", "people", "perfect", "perform",
	"perhaps", "period", "permit", "person", "phrase", "picture",
	"pigeon", "pillow", "pirate", "planet", "plastic", "player",
	"pleasure", "pocket", "poetry", "police", "policy", "portion",
	"possible", "poverty", "powder", "prefer", "prepare", "present",
	"pretty", "prevent", "primary", "prince", "printer", "prison",
	"private", "problem", "process", "produce", "profile", "program",
	"project", "promise", "prompt", "protect", "proud", "provide",
	"public", "purple", "purpose", "puzzle", "quality", "quarter",
	"question", "quiet", "rabbit", "radio", "random", "rather", "reason",
	"recall", "receive", "recent", "record", "recover", "reduce",
	"reflect", "region", "regular", "relate", "release", "remain",
	"remember", "remind", "remote", "remove", "render", "repair",
	"repeat", "replace", "reply", "report", "request", "rescue",
	"resist", "resort", "resource", "respect", "respond", "result",
	"retain", "retire", "return", "reveal", "review", "reward", "ribbon",
	"ridge", "rocket", "romance", "rotate", "rough", "route", "royal",
	"rubber", "sacred", "salary", "sample", "satisfy", "scale", "scene",
	"schedule", "science", "scissors", "screen", "search", "season",
	"secret", "section", "secure", "select", "senior", "sense",
	"sentence", "series", "service", "settle", "shadow", "shallow",
	"shelter", "shield", "shoulder", "signal", "silver", "similar",
	"simple", "single", "sister", "skill", "slight", "smooth", "society",
	"soldier", "solution", "someone", "source", "special", "species",
	"specific", "spirit", "sponsor", "spread", "spring", "square",
	"stable", "stadium", "standard", "statue", "steady", "stomach",
	"strange", "stream", "street", "stretch", "strict", "student",
	"studio", "submit", "subtle", "success", "sudden", "suffer",
	"suggest", "summer", "supply", "support", "suppose", "surface",
	"surprise", "survey", "survive", "suspect", "sustain", "sweater",
	"symbol", "system", "target", "temper", "temple", "tenant",
	"tender", "tennis", "theory", "thereby", "thirsty", "thought",
	"thread", "throat", "thunder", "ticket", "timber", "tissue",
	"tomato", "tongue", "tonight", "toward", "tower", "tractor",
	"traffic", "trailer", "transfer", "travel", "treaty", "trigger",
	"trouble", "trumpet", "tunnel", "twelve", "unable", "uncle",
	"unique", "united", "universe", "unknown", "update", "upload",
	"upset", "urban", "usage", "useful", "valley", "vapor", "variety",
	"vehicle", "version", "victory", "village", "violet", "virtual",
	"vision", "visitor", "vital", "voyage", "wander", "warmth", "weapon",
	"weather", "weekly", "welcome", "welfare", "western", "whisper",
	"window", "winter", "wisdom", "wonder", "wooden", "worker",
	"worried", "wrestle", "yellow", "yield", "zebra",
};

const int bsdgame_words_count = sizeof(bsdgame_words) / sizeof(bsdgame_words[0]);
