#!/usr/bin/env bash
# hangman/build.sh - see PORT for why build=script.
set -euo pipefail

PORT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

# mports.sh expects the finished archive at $W/<lib> where $W is the port's
# OWN work directory (ports/.work/hangman), not $MPORTS_OUT/lib (that install
# copy is mports.sh's own job, done after this script returns and the
# anti-no-op nm check passes). srcdir=bsd-games-2.17/hangman has TWO path
# components, so the work root is two dirname() calls above $MPORTS_SRC, not
# one (one dirname() only strips "hangman", leaving ".../bsd-games-2.17").
# Same derivation the ncurses port's build.sh documents for its one-component
# srcdir case.
S="${MPORTS_SRC:?hangman/build.sh: MPORTS_SRC unset}"
W="$(dirname "$(dirname "$S")")"

# pathnames.h: upstream ships only pathnames.h.in (an autoconf template,
# never run here). hangman only needs _PATH_DICT to exist as a symbol
# (extern.c initialises Dict_name from it); the patches in this port removed
# every place that actually opens the path, so the value itself is inert.
echo "hangman/build.sh: writing pathnames.h"
cat > pathnames.h <<'EOF'
/* generated by userland/ports/hangman/build.sh - no configure is run here.
 * hangman no longer opens a dictionary file (see the 0001/0002 patches);
 * this value is never dereferenced, only assigned to Dict_name. */
#define _PATH_DICT "unused"
EOF

CFLAGS="$MPORTS_CFLAGS -I$PORT_DIR/shim -DBSDGAME_PROGNAME=\"hangman\" -w"

SRCS="main setup playgame getword getguess endgame prdata prman prword extern"
for f in $SRCS; do
  gcc $CFLAGS -c "$f.c" -o "$WORKDIR/hg_$f.o"
done
gcc $CFLAGS -c "$PORT_DIR/bsdgame_compat.c" -o "$WORKDIR/hg_compat.o"
gcc $CFLAGS -c "$PORT_DIR/bsdgame_words.c" -o "$WORKDIR/hg_words.o"

rm -f "$W/libhangman.a"
ar rcs "$W/libhangman.a" "$WORKDIR"/hg_*.o
echo "hangman/build.sh: OK -> $W/libhangman.a"
