/*
 *     XaoS, a fast portable realtime fractal zoomer
 *                  Copyright (C) 1996,1997 by
 *
 *      Jan Hubicka          (hubicka@paru.cas.cz)
 *      Thomas Marsh         (tmarsh@austin.ibm.com)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * ui_maytera.c - MayteraOS platform driver (#745,
 * docs/PORTABILITY_HOMEBREW_SNAPCRAFT_ASSESSMENT.md Tier 3 #16). This is the
 * ONLY file in this port that is not upstream XaoS 3.6: it plugs the
 * upstream `struct ui_driver` contract (src/include/ui.h) into MayteraOS's
 * compositor window protocol, the same "one small platform layer, rest of
 * the source untouched" shape as userland/apps/doom/i_maytera.c +
 * i_video.c. Modelled closely on upstream's own
 * src/ui/ui-drv/win32/ui_win32.c (a bitmap-blit, true-colour, single-window
 * driver - the closest of the seven upstream drivers to what a compositor
 * window is) and src/ui/ui-drv/template/ui_template.c (the field list).
 *
 * KEYBOARD MODEL, for a keyboard-only verification pass (mouse injection is
 * unreliable in this project's test VMs, #334): real XaoS is mouse-first
 * (hold left button to zoom in toward the cursor, right button to zoom out,
 * drag to pan). BUTTON1/BUTTON2/BUTTON3 (src/include/ui.h) are exactly the
 * bits `ui_mouse()` (src/ui/ui.c) already reads every frame, so holding 'Z'
 * or 'X' here synthesizes BUTTON1/BUTTON3 at the tracked cursor position -
 * it drives the SAME zoom code path a real mouse would, just fed from the
 * keyboard. Arrow keys move that synthetic cursor (for aiming) AND are
 * ALSO passed through as the `k` bitmask ui_mouse() reads for its own
 * iteration-count/zoom-speed tuning (bit1=LEFT,2=RIGHT,4=UP,8=DOWN,
 * matching ui_win32.c's arrowsPressed convention) so no upstream behaviour
 * is bypassed, only reachable without a mouse as well as with one.
 */
#include "aconfig.h"
#ifdef MAYTERA_DRIVER
#include <ui.h>
#include <stdlib.h>
#include <string.h>

/* LIBC_DIR (userland/libc) is on the include path via -I in the Makefile,
 * same as every other userland app/port; no relative dot-dot path needed. */
#include "syscall.h"
#include "gui.h"

#define XAOS_W 640
#define XAOS_H 480

/* BUTTON1/2/3 are #undef+#redefine'd by ui.h to 256/512/1024; they are NOT
 * MayteraOS's MOUSE_BUTTON_LEFT(1)/RIGHT(2)/MIDDLE(4) from gui.h, which is
 * why this file only ever compares gui_event_t.mouse_buttons against the
 * MOUSE_BUTTON_* names and only ever WRITES BUTTON1/2/3 into the ints this
 * driver hands back to the engine. Keeping the two namespaces textually
 * distinct (never casting one straight into the other) is the whole
 * safeguard.
 */

static int win_handle = -1;
static uint32_t *buf[2];       /* the two XaoS double-buffers  */
static int front = 0;          /* which of buf[] is "on screen" */
static int mouse_x = XAOS_W / 2, mouse_y = XAOS_H / 2;
static int mouse_buttons = 0;  /* BUTTON1/2/3 bits, synthetic or real */
static int arrows = 0;         /* 1=left 2=right 4=up 8=down, held state */
static int have_quit = 0;

#define CURSOR_STEP 6

static int maytera_set_color(int r, int g, int b, int init)
{
    (void) r; (void) g; (void) b; (void) init;
    return (-1);               /* true-colour: no palette index to hand back */
}

static void maytera_setpalette(ui_palette pal, int start, int end)
{
    (void) pal; (void) start; (void) end;
}

static void maytera_print(int x, int y, const char *text)
{
    /* Upstream's own win32 driver routes this to the OS window-title bar,
     * not an on-canvas overlay (SetWindowText(), not TextOut()); there is no
     * MayteraOS syscall to retitle a live window after win_create(), so this
     * is the same no-op the upstream template driver documents for exactly
     * this field. Status text (iteration count, "please wait" etc.) is
     * still generated by the engine; it is just not drawn anywhere, same as
     * a build with UI_NOGUI text disabled. */
    (void) x; (void) y; (void) text;
}

static void maytera_display(void)
{
    if (win_handle < 0 || !buf[front])
        return;
    syscall5(SYS_WIN_BLIT, win_handle, 0, 0,
             (uint32_t) XAOS_W | ((uint32_t) XAOS_H << 16),
             (uint64_t) buf[front]);
    win_invalidate(win_handle);
}

static void maytera_flip_buffers(void)
{
    front ^= 1;
}

static void maytera_free_buffers(char *b1, char *b2)
{
    (void) b1; (void) b2;
    if (buf[0]) { sys_munmap(buf[0], (unsigned long) XAOS_W * XAOS_H * 4); buf[0] = NULL; }
    if (buf[1]) { sys_munmap(buf[1], (unsigned long) XAOS_W * XAOS_H * 4); buf[1] = NULL; }
}

static int maytera_alloc_buffers(char **b1, char **b2, void **data)
{
    buf[0] = (uint32_t *) sys_mmap(NULL, (unsigned long) XAOS_W * XAOS_H * 4, 3, 0);
    buf[1] = (uint32_t *) sys_mmap(NULL, (unsigned long) XAOS_W * XAOS_H * 4, 3, 0);
    if (!buf[0] || !buf[1]) {
        maytera_free_buffers(NULL, NULL);
        return 0;
    }
    front = 0;
    *b1 = (char *) buf[0];
    *b2 = (char *) buf[1];
    *data = NULL;
    return XAOS_W * 4;         /* bytes per scanline */
}

static void maytera_getsize(int *w, int *h)
{
    *w = XAOS_W;
    *h = XAOS_H;
}

static void maytera_getmouse(int *x, int *y, int *b)
{
    *x = mouse_x;
    *y = mouse_y;
    *b = mouse_buttons;
}

static void maytera_mousetype(int type)
{
    (void) type;               /* no cursor-shape hook exposed by SYS_WIN_* yet */
}

static void clampcursor(void)
{
    if (mouse_x < 0) mouse_x = 0;
    if (mouse_y < 0) mouse_y = 0;
    if (mouse_x >= XAOS_W) mouse_x = XAOS_W - 1;
    if (mouse_y >= XAOS_H) mouse_y = XAOS_H - 1;
}

static void
maytera_processevents(int wait, int *mx, int *my, int *mb, int *k)
{
    gui_event_t ev;
    int r;

    if (win_handle >= 0) {
        while ((r = win_get_event(win_handle, &ev, wait ? -1 : 0)) > 0) {
            wait = 0;           /* only block for the FIRST poll of a batch */
            switch (ev.type) {
            case EVENT_WINDOW_CLOSE:
                have_quit = 1;
                break;
            case EVENT_MOUSE_MOVE:
                mouse_x = ev.mouse_x;
                mouse_y = ev.mouse_y;
                clampcursor();
                break;
            case EVENT_MOUSE_DOWN:
                mouse_x = ev.mouse_x;
                mouse_y = ev.mouse_y;
                clampcursor();
                if (ev.mouse_buttons & MOUSE_BUTTON_LEFT)
                    mouse_buttons |= BUTTON1;
                if (ev.mouse_buttons & MOUSE_BUTTON_RIGHT)
                    mouse_buttons |= BUTTON3;
                if (ev.mouse_buttons & MOUSE_BUTTON_MIDDLE)
                    mouse_buttons |= BUTTON2;
                break;
            case EVENT_MOUSE_UP:
                if (!(ev.mouse_buttons & MOUSE_BUTTON_LEFT))
                    mouse_buttons &= ~BUTTON1;
                if (!(ev.mouse_buttons & MOUSE_BUTTON_RIGHT))
                    mouse_buttons &= ~BUTTON3;
                if (!(ev.mouse_buttons & MOUSE_BUTTON_MIDDLE))
                    mouse_buttons &= ~BUTTON2;
                break;
            case EVENT_KEY_DOWN:
                switch (ev.keycode) {
                case GUI_KEY_LEFT:  arrows |= 1; break;
                case GUI_KEY_RIGHT: arrows |= 2; break;
                case GUI_KEY_UP:    arrows |= 4; break;
                case GUI_KEY_DOWN:  arrows |= 8; break;
                case GUI_KEY_ESC:   have_quit = 1; break;
                default:
                    if (ev.key_char == 'z' || ev.key_char == 'Z')
                        mouse_buttons |= BUTTON1;   /* hold to zoom in */
                    else if (ev.key_char == 'x' || ev.key_char == 'X')
                        mouse_buttons |= BUTTON3;   /* hold to zoom out */
                    else if (ev.key_char)
                        ui_key((int) (unsigned char) ev.key_char);
                    break;
                }
                break;
            case EVENT_KEY_UP:
                switch (ev.keycode) {
                case GUI_KEY_LEFT:  case GUI_KEY_LEFT_REL:  arrows &= ~1; break;
                case GUI_KEY_RIGHT: case GUI_KEY_RIGHT_REL: arrows &= ~2; break;
                case GUI_KEY_UP:    case GUI_KEY_UP_REL:    arrows &= ~4; break;
                case GUI_KEY_DOWN:  case GUI_KEY_DOWN_REL:  arrows &= ~8; break;
                default:
                    if (ev.key_char == 'z' || ev.key_char == 'Z')
                        mouse_buttons &= ~BUTTON1;
                    else if (ev.key_char == 'x' || ev.key_char == 'X')
                        mouse_buttons &= ~BUTTON3;
                    break;
                }
                break;
            default:
                break;
            }
        }
    }

    if (arrows & 1) mouse_x -= CURSOR_STEP;
    if (arrows & 2) mouse_x += CURSOR_STEP;
    if (arrows & 4) mouse_y -= CURSOR_STEP;
    if (arrows & 8) mouse_y += CURSOR_STEP;
    clampcursor();

    if (have_quit)
        ui_quit();              /* NORETURN: never returns */

    *mx = mouse_x;
    *my = mouse_y;
    *mb = mouse_buttons;
    *k = arrows;
}

static int maytera_init(void)
{
    win_handle = win_create("XaoS", 100, 100, XAOS_W, XAOS_H);
    if (win_handle < 0)
        return 0;
    mouse_x = XAOS_W / 2;
    mouse_y = XAOS_H / 2;
    mouse_buttons = 0;
    arrows = 0;
    have_quit = 0;
    return 1;
}

static void maytera_uninitialise(void)
{
    maytera_free_buffers(NULL, NULL);
    if (win_handle >= 0) {
        win_destroy(win_handle);
        win_handle = -1;
    }
}

static struct params maytera_params[] = {
    {"", P_HELP, NULL, "MayteraOS driver options:"},
    {NULL, 0, NULL, NULL}
};

struct ui_driver maytera_driver = {
    "MayteraOS",
    maytera_init,
    maytera_getsize,
    maytera_processevents,
    maytera_getmouse,
    maytera_uninitialise,
    maytera_set_color,
    maytera_setpalette,
    maytera_print,
    maytera_display,
    maytera_alloc_buffers,
    maytera_free_buffers,
    maytera_flip_buffers,
    maytera_mousetype,
    NULL,                       /* flush */
    8, 16,                      /* textwidth, textheight: FONT_WIDTH/FONT_HEIGHT, gui.h */
    maytera_params,
    0,                          /* flags: fixed-size window, no runtime resize */
    0.0, 0.0,                   /* physical screen size: n/a, windowed */
    0, 0,                       /* resolution: n/a, windowed (template's convention) */
    UI_TRUECOLOR,
    0, 255, 255,                /* palettestart, paletteend, maxentries: unused (true-colour) */
    0xff0000, 0x00ff00, 0x0000ff,  /* rmask/gmask/bmask: MayteraOS's 0x00RRGGBB, matches gui.h COLOR_* */
    NULL,                       /* gui_driver */
    NULL                        /* image_driver */
};

#endif /* MAYTERA_DRIVER */
