// SPDX-License-Identifier: MIT
// Copyright (c) MayteraOS contributors.
// Full license text: userland/libc/LICENSE (MIT License).
//
// ctl - the contract debug client (#233).
//
// WHY THIS EXISTS
//
// Before this, verifying that a UI change did anything meant injecting a
// pixel click and reading a screendump. That is why a Settings hit-box fix
// nearly shipped unverified and why a 128-control audit had to be done by
// reading source. This turns "did that control do anything?" into a question
// you can ASK:
//
//     ctl get settings clock.use_24hour
//     ctl set settings clock.use_24hour 0
//     ctl call calc key.7
//     ctl get calc display
//
// HOW IT REACHES THE APP, and why there is no new syscall
//
// It spawns the app's own binary with `--contract <verb> ...`. The app answers
// from the SAME table that draws and hit-tests its controls, before it creates
// a window, and exits. Consequences worth stating:
//
//   - no new syscall (SYS_SPAWN_REDIR 247 already gives argv plus output
//     capture), so none of the five-place syscall registration applies and
//     repo-guard's --strict syscall lint has nothing new to check;
//   - it works whether or not a GUI instance of the app is running, which a
//     message-passing design would not: the message would have nobody to
//     answer it;
//   - it cannot drift from the app, because it IS the app answering.
//
// The alternative designs were considered and rejected for concrete reasons,
// recorded in docs/CONTRACT_API.md section 3: kernel IPC (kernel/ipc/msg.c)
// has a live named-port registry with ZERO callers, no unregister, no cleanup
// on process death and a documented busy-yield in msg_recv() (msg.h:65-70,
// blocked on #515); a contract syscall would need the kernel to hold policy
// for 182 userland apps.
//
// The app's output lands on fd 1, which the kernel's fd-1 fallback
// (kernel/proc/fdlayer.c:1468) also writes to the serial console, so a harness
// with no GUI can read every result off the serial socket.

#include "stdio.h"
#include "string.h"
#include "stdlib.h"
#include "unistd.h"
#include "fcntl.h"
#include "syscall.h"
#include "contract.h"
#include "aiclient.h"   // #235: the AI path, for the aipath differential
#include "aicap.h"      // #235: consent comes from a file only root can write

// #235: renamed off /AITOOLS/INDEX.YML, which is the AI TOOL index and was
// already in use. See libc/ctinvoke.c for the measurement.
#define CTL_INDEX  "/AITOOLS/CONTRACTS.YML"

static void usage(void) {
    printf("ctl - MayteraOS contract debug client (#233)\n");
    printf("usage:\n");
    printf("  ctl apps                      list apps that declare a contract\n");
    printf("  ctl list     <app>            list the app's contract item names\n");
    printf("  ctl describe <app>            the app's full declaration\n");
    printf("  ctl get      <app> <name>     read one item\n");
    printf("  ctl set      <app> <name> <v> write one item\n");
    printf("  ctl call     <app> <name> ... invoke one action\n");
    printf("  ctl path     <app>            show the binary ctl would spawn\n");
    printf("  ctl aipath   get|set <name> [v] drive the SAME item through the AI\n");
    printf("                                tool executor and show both answers\n");
    printf("\nrisk classes: safe (ungated), guarded (needs a capability token\n");
    printf("or consent, via libc/aicap.c), denied (declared, never invocable).\n");
}

// Ask the app, then replay its answer verbatim on our own stdout. We do NOT
// reinterpret it: the app's line IS the answer, and a client that paraphrased
// would be a second description of the result.
//
// #235: the spawn/capture/fallback machinery this used to carry inline now
// lives in libc as contract_invoke(), because libc/aiclient.c's settings tools
// became a second caller. Two copies of "how do I reach an app's contract"
// would be exactly the fault this API exists to remove.
static int run_contract(const char *app, int argc, char **argv) {
    static char out[4096];
    int rc = contract_invoke(app, argc, argv, out, (int)sizeof(out));
    size_t n = strlen(out);
    if (n) write(1, out, n);
    return rc;
}

// `ctl apps` reads the generated index. It deliberately does NOT probe every
// binary in /APPS: spawning 182 apps to ask whether they have a contract would
// launch every GUI app that does not.
static int list_apps(void) {
    int fd = open(CTL_INDEX, O_RDONLY);
    if (fd < 0) {
        printf("ctl: %s is missing.\n", CTL_INDEX);
        printf("ctl: it is generated by tools/contract-lint/contract-lint.py and\n");
        printf("ctl: installed by the golden build; without it, name an app\n");
        printf("ctl: explicitly (ctl describe settings).\n");
        return CT_ERR_USAGE;
    }
    char buf[8192];
    long n;
    while ((n = read(fd, buf, sizeof(buf))) > 0) write(1, buf, (size_t)n);
    close(fd);
    return CT_OK;
}

// ---------------------------------------------------------------------------
// `ctl aipath` - the differential that keeps #235 honest.
//
// libc/aiclient.c's settings.get / settings.set used to be a SECOND
// implementation of the Settings surface: a hardcoded if-else chain calling the
// kernel setters, covering a different key set from the real one, reachable only
// from AI chat. #235 made it delegate to /APPS/SETTINGS --contract, so there is
// one implementation. This verb PROVES that, on the running system, in one
// command: it drives the item through aiclient_run_action() - the exact
// executor the AI's ACTION lines reach, including the #293 capability gate and
// the audit record - and then reads the item back through the ordinary contract
// path, and prints both.
//
// If the two ever diverge again, this goes from two agreeing lines to two
// disagreeing ones, which is the whole point of having it rather than a claim
// in a document.
//
// CONSENT IS NOT AUTO-GRANTED. settings.set is HIGH-risk, and with no consent
// callback aicap fails closed - correctly, since a headless caller must not
// mint its own authority. The callback registered here does nothing but consume
// a decision PRE-SEEDED in /CONFIG/AICONSENT.CFG (aicap_preseed_consent(), the
// documented headless pattern), and /CONFIG is root-writable only. No file, no
// authority, and the run reports CAPABILITY_DENIED rather than silently
// succeeding.
// Pull a string field out of the AI path's JSON observation. Eight lines, not a
// parser: the observation is emitted by libc/aiclient.c in a fixed shape.
static int ct_json_str(const char *json, const char *key, char *out, int ocap) {
    char pat[48];
    snprintf(pat, sizeof(pat), "\"%s\":\"", key);
    const char *p = strstr(json, pat);
    if (!p) { if (ocap > 0) out[0] = 0; return 0; }
    p += strlen(pat);
    int o = 0;
    while (*p && *p != '"' && o < ocap - 1) out[o++] = *p++;
    out[o] = 0;
    return o > 0;
}

static int ctl_consent(const char *tool_id, const char *cap, int risk,
                       const char *args, const char *target) {
    (void)risk; (void)args; (void)target;
    int d = aicap_preseed_consent(tool_id, cap);
    return (d >= 0) ? d : AICAP_CONSENT_DENY;
}

static int ai_path(int argc, char **argv) {
    // argv: aipath <get|set> <name> [value]
    if (argc < 4) { usage(); return CT_ERR_USAGE; }
    const char *verb = argv[2];
    const char *name = argv[3];
    const char *val  = (argc > 4) ? argv[4] : "";

    aicap_init();
    aicap_set_consent_cb(ctl_consent);

    char args[320];
    if (!strcmp(verb, "set"))
        snprintf(args, sizeof(args), "{\"key\":\"%s\",\"value\":\"%s\"}", name, val);
    else
        snprintf(args, sizeof(args), "{\"key\":\"%s\"}", name);

    static char obs[4096];
    int az = aiclient_run_action(!strcmp(verb, "set") ? "settings.set" : "settings.get",
                                 args, obs, (int)sizeof(obs));
    printf("ai-path   %s %s -> %s\n", verb, name, obs);
    if (az != 0)
        printf("ai-path   authorization outcome %d (%s); pre-seed "
               "/CONFIG/AICONSENT.CFG to allow a headless HIGH-risk write\n",
               az, aicap_code(az));

    // Now the ordinary contract path, reading the SAME item. The name to read
    // back is the one the AI path RESOLVED to, not the one we were given: a
    // caller may legitimately say "brightness" and the resolution to
    // "display.brightness" happens inside aiclient, against the app's own item
    // list. Reading back the raw key would compare the two paths on different
    // items, which is worse than not comparing them at all.
    char resolved[CT_NAME_MAX];
    if (!ct_json_str(obs, "setting", resolved, (int)sizeof(resolved)) || !resolved[0])
        strlcpy(resolved, name, sizeof(resolved));

    char *rv[2]; rv[0] = (char *)"get"; rv[1] = resolved;
    static char line[1024];
    contract_invoke("settings", 2, rv, line, (int)sizeof(line));
    printf("ctl-path  get %s -> %s", resolved, line);
    return CT_OK;
}

int main(int argc, char **argv) {
    if (argc < 2) { usage(); return CT_ERR_USAGE; }
    const char *verb = argv[1];

    if (!strcmp(verb, "-h") || !strcmp(verb, "--help") || !strcmp(verb, "help")) {
        usage(); return CT_OK;
    }
    if (!strcmp(verb, "apps")) return list_apps();
    if (!strcmp(verb, "aipath")) return ai_path(argc, argv);

    if (argc < 3) { usage(); return CT_ERR_USAGE; }
    const char *app = argv[2];

    if (!strcmp(verb, "path")) {
        char p[128]; contract_app_path(app, p, (int)sizeof(p));
        printf("%s\n", p);
        return CT_OK;
    }
    if (!strcmp(verb, "list") || !strcmp(verb, "describe") || !strcmp(verb, "probe")) {
        char *rest[1]; rest[0] = (char *)verb;
        return run_contract(app, 1, rest);
    }
    if (!strcmp(verb, "get") || !strcmp(verb, "set") || !strcmp(verb, "call")) {
        char *rest[24];
        int rc = 0;
        rest[rc++] = (char *)verb;
        for (int i = 3; i < argc && rc < 22; i++) rest[rc++] = argv[i];
        return run_contract(app, rc, rest);
    }
    usage();
    return CT_ERR_USAGE;
}
