#!/usr/bin/env bash
# ports/jq/build.sh - the build=script step for the jq port (Tier 2 item #10 of
# docs/PORTABILITY_HOMEBREW_SNAPCRAFT_ASSESSMENT.md).
#
# WHY THIS PORT IS build=script AND NOT build=objects. Three structural reasons,
# each of which a plain `sources=` list cannot express:
#
#  1. GENERATED SOURCES. jq compiles two files that DO NOT EXIST in the tarball
#     and are produced from data at build time: src/builtin.inc (jq's standard
#     library, src/builtin.jq, turned into a C octal-byte array by the exact
#     od/sed pipeline in upstream's Makefile.am) and src/config_opts.inc (the
#     JQ_CONFIG string main.c prints for `jq --build-configuration`). A
#     `sources` list is verified to exist IN THE UNPACKED TARBALL, so neither
#     could appear there.
#
#  2. TWO PROJECTS, ONE ARCHIVE. jq's regex builtins (test/match/sub/gsub/
#     splits/capture) are implemented against Oniguruma, which jq bundles under
#     vendor/oniguruma. Rather than a second tarball, this port compiles the
#     bundled copy (exactly the source list upstream's vendor/oniguruma builds
#     with --with-oniguruma=builtin) into the SAME libjq.a. The anti-no-op
#     symbol check in PORT then proves BOTH halves are really in the archive
#     (onig_new/onig_search prove Oniguruma landed; a build that dropped the
#     regex engine fails HERE, not at a consumer's confused runtime).
#
#  3. Oniguruma needs a config.h (regenc.h includes it unconditionally), which
#     autoconf would generate. We write the small, correct one for this target
#     as DATA below instead of running ./configure.
#
# Contract from mports.sh: cwd = the unpacked srcdir; MPORTS_CFLAGS carries the
# userland cross-build flags PLUS this port's cflags= (the jq HAVE_* set);
# MPORTS_SRC is the unpacked srcdir; MPORTS_OUT is the install tree. After we
# return, mports looks for the archive at $(dirname MPORTS_SRC)/<lib> and proves
# every symbol promised in PORT is defined in it.
#
# main() IS DELIBERATELY IN THE ARCHIVE. jq is fundamentally a program; libjq.a
# here is "the whole jq, relinkable". crt0's reference to main pulls main.o and,
# through it, the rest. An archive member is only extracted to satisfy an
# undefined reference, so a future consumer that links libjq.a as a LIBRARY
# behind its own main() never pulls jq's main.o: no conflict either way. This is
# why the app (userland/apps/jq) is a link-only Makefile with no flag or header
# duplication - the compile flags live in exactly one place, PORT + this script.
set -euo pipefail

: "${MPORTS_CFLAGS:?mports must pass MPORTS_CFLAGS}"
: "${MPORTS_SRC:?mports must pass MPORTS_SRC}"

WORKDIR="$(dirname "$MPORTS_SRC")"   # where mports expects libjq.a
LIB="$WORKDIR/libjq.a"
ONIG_DIR="vendor/oniguruma/src"

echo "jq/build.sh: generating src/builtin.inc from src/builtin.jq"
# The EXACT pipeline from jq's Makefile.am (od -v octal bytes -> comma list).
# A hand-rolled variant would be a place jq's standard library could silently
# differ from upstream, so this mirrors it character for character.
mkdir -p src
od -v -A n -t o1 -- src/builtin.jq | \
  sed -e 's/$/ /' \
      -e 's/\([0123456789]\) /\1, /g' \
      -e 's/ $//' \
      -e 's/ 0/  0/g' \
      -e 's/ \([123456789]\)/ 0\1/g' > src/builtin.inc

echo "jq/build.sh: generating src/config_opts.inc"
# main.c #includes this to print the build configuration. We do not run
# ./config.status, so record the honest one-line summary of how this jq was
# built rather than a shell-configure dump.
printf '#define JQ_CONFIG "MayteraOS mports (bundled oniguruma, decNumber, no threads)"\n' > src/config_opts.inc

echo "jq/build.sh: writing Oniguruma config.h for the MayteraOS target"
# regenc.h includes "config.h" in every Oniguruma translation unit. These are
# the values autoconf would compute for this LP64, little-endian, hardware-float
# userland: stdint/inttypes/sys-types/unistd/alloca headers all present in the
# shared libc; sizes are the x86-64 LP64 ABI. We do NOT enable USE_POSIX_API or
# ONIG_DEBUG_STATISTICS, so no sys/time.h or POSIX regcomp veneer is pulled.
cat > "$ONIG_DIR/config.h" <<'CFGEOF'
/* Generated by MayteraOS ports/jq/build.sh - see that file for rationale. */
#define HAVE_STDINT_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STDIO_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define HAVE_ALLOCA_H 1
#define HAVE_ALLOCA 1
#define STDC_HEADERS 1
#define SIZEOF_INT 4
#define SIZEOF_LONG 8
#define SIZEOF_LONG_LONG 8
#define SIZEOF_VOIDP 8
CFGEOF

# ---------------------------------------------------------------------------
# Oniguruma object list: EXACTLY libonig_la_SOURCES from vendor/oniguruma's own
# src/Makefile.am, in upstream order. NOT a glob of src/*.c, which would sweep
# in mktable.c (a standalone table-generator with its own main()), the
# regposix.c/regposerr.c POSIX veneer (which redefines regcomp/regexec/regfree
# and would collide the day the libc grows a POSIX regex), and the *_data.c /
# koi8.c files that are #included by other units rather than compiled alone.
# ---------------------------------------------------------------------------
ONIG_SRCS="regparse regcomp regexec regenc regerror regext regsyntax regtrav \
regversion st reggnu unicode unicode_unfold_key unicode_fold1_key \
unicode_fold2_key unicode_fold3_key ascii utf8 utf16_be utf16_le utf32_be \
utf32_le euc_jp euc_jp_prop sjis sjis_prop iso8859_1 iso8859_2 iso8859_3 \
iso8859_4 iso8859_5 iso8859_6 iso8859_7 iso8859_8 iso8859_9 iso8859_10 \
iso8859_11 iso8859_13 iso8859_14 iso8859_15 iso8859_16 euc_tw euc_kr big5 \
gb18030 koi8_r cp1251 onig_init"

# ---------------------------------------------------------------------------
# libjq object list: LIBJQ_SRC from jq's own Makefile.am (minus nothing: it is
# a library list already, with no main()), PLUS the two BUILT_SOURCES lexer.c
# and parser.c that upstream ships pre-generated in the release tarball, PLUS
# vendor/decNumber (jq's arbitrary-precision decimal, part of LIBJQ_SRC). main.c
# is compiled separately below and archived so crt0 can pull it.
# ---------------------------------------------------------------------------
JQ_SRCS="jv jv_alloc jv_parse jv_print jv_dtoa jv_unicode jv_aux jv_file util \
locfile bytecode compile execute builtin linker lexer parser jv_dtoa_tsd jq_test"

OBJS=()

echo "jq/build.sh: compiling Oniguruma (${ONIG_DIR})"
# Upstream vendored code: -w so its warnings do not bury a real one from jq. It
# needs HAVE_CONFIG_H and its own src on the include path; the jq HAVE_* that
# ride in MPORTS_CFLAGS are inert here (Oniguruma never tests them).
for f in $ONIG_SRCS; do
  gcc $MPORTS_CFLAGS -DHAVE_CONFIG_H -I"$ONIG_DIR" -w -c "$ONIG_DIR/$f.c" -o "$WORKDIR/onig_$f.o"
  OBJS+=("$WORKDIR/onig_$f.o")
done

echo "jq/build.sh: compiling libjq"
# jq's own translation units. MPORTS_CFLAGS carries the HAVE_* set (PORT cflags),
# -DIEEE_8087 (jv_dtoa selects float byte order at compile time and errors if
# none is given), and the include paths. -w because upstream jq trips -Wextra;
# our own added code is none here (the port ships jq unaltered).
for f in $JQ_SRCS; do
  gcc $MPORTS_CFLAGS -I. -Isrc -Ivendor -I"$ONIG_DIR" -w -c "src/$f.c" -o "$WORKDIR/jq_$f.o"
  OBJS+=("$WORKDIR/jq_$f.o")
done

echo "jq/build.sh: compiling vendor/decNumber"
for f in decNumber decContext; do
  gcc $MPORTS_CFLAGS -I. -Isrc -Ivendor -w -c "vendor/decNumber/$f.c" -o "$WORKDIR/$f.o"
  OBJS+=("$WORKDIR/$f.o")
done

echo "jq/build.sh: compiling the jq CLI main() (archived, see header)"
gcc $MPORTS_CFLAGS -I. -Isrc -Ivendor -I"$ONIG_DIR" -w -c src/main.c -o "$WORKDIR/main.o"
OBJS+=("$WORKDIR/main.o")

echo "jq/build.sh: archiving libjq.a"
rm -f "$LIB"
ar rcs "$LIB" "${OBJS[@]}"

echo "jq/build.sh: done -> $LIB"
