// GENERATED by tools/coreutils-oracle/coreutils-oracle.sh --vm-table
// on 2026-08-13T22:04:17Z. DO NOT HAND-EDIT: regenerate it.
//
// Every 'want' below is the output of THIS HOST's GNU coreutils:
//   wc (GNU coreutils) 9.1
//
// The fixture hashes are checked by toolchk BEFORE any case runs, so a
// fixture that has drifted from the one these answers were generated
// against reports itself instead of reporting tool failures.

struct vmfix { const char *name; const char *sha256; };
static const struct vmfix VMFIX[] = {
	{ "T4A.TXT", "833940e53452e86ad3cf12deb4054606301b43cec7607677dab4625777c7cee3" },
	{ "T4B.TXT", "bdf336f71bf1ad7b7a4849bbdbb03824a6d59fe5cf5ef55e88791dc8207c41aa" },
	{ "T4T.TSV", "b8d39c7ad759ccff921a9e0afdfc8fbba841f1d6df3dd9b14fc55d1e5f08213c" },
	{ "T4NUM.TXT", "423bd402e4a491a051903a6abd500e319bf0b0674ff736647002142bcc8d335c" },
	{ "T4BIG.TXT", "f6351f5ead9a700e34275480b3856ea738122a7c57bdeb744a631251c069587a" },
	{ "T4SORT.TXT", "9591a859f329e772608f380f79b528683e38f6161fe89808160ae7234e25dc38" },
};

struct vmcase { const char *name; const char *path; char *argv[8];
                int collapse; int limit; const char *want; };
static const struct vmcase VMCASES[] = {
	{ "wc-two", "/APPS/WC", { "wc", "T4A.TXT", "T4B.TXT", 0 }, 1, 0,
	  "4 4 26 T4A.TXT\n2 2 12 T4B.TXT\n6 6 38 total\n" },
	{ "wc-lines", "/APPS/WC", { "wc", "-l", "T4A.TXT", "T4B.TXT", 0 }, 1, 0,
	  "4 T4A.TXT\n2 T4B.TXT\n6 total\n" },
	{ "head-two-files", "/APPS/HEAD", { "head", "-n", "1", "T4A.TXT", "T4B.TXT", 0 }, 0, 0,
	  "==> T4A.TXT <==\nalpha\n\n==> T4B.TXT <==\nzulu\n" },
	{ "head-obsolete", "/APPS/HEAD", { "head", "-2", "T4A.TXT", 0 }, 0, 0,
	  "alpha\nbravo\n" },
	{ "head-bytes", "/APPS/HEAD", { "head", "-c", "5", "T4A.TXT", 0 }, 0, 0,
	  "alpha" },
	{ "tail-past-64k", "/APPS/TAIL", { "tail", "-n", "3", "T4BIG.TXT", 0 }, 0, 0,
	  "19998\n19999\n20000\n" },
	{ "tail-default-big", "/APPS/TAIL", { "tail", "T4BIG.TXT", 0 }, 0, 0,
	  "19991\n19992\n19993\n19994\n19995\n19996\n19997\n19998\n19999\n20000\n" },
	{ "tail-two-files", "/APPS/TAIL", { "tail", "-n", "1", "T4A.TXT", "T4B.TXT", 0 }, 0, 0,
	  "==> T4A.TXT <==\ndelta\n\n==> T4B.TXT <==\nyankee\n" },
	{ "tail-from-line", "/APPS/TAIL", { "tail", "-n", "+19999", "T4BIG.TXT", 0 }, 0, 0,
	  "19999\n20000\n" },
	{ "cut-field-list", "/APPS/CUT", { "cut", "-f1,3", "T4T.TSV", 0 }, 0, 0,
	  "x\tz\n1\t3\n" },
	{ "cut-field-range", "/APPS/CUT", { "cut", "-f2-", "T4T.TSV", 0 }, 0, 0,
	  "y\tz\n2\t3\n" },
	{ "cut-chars", "/APPS/CUT", { "cut", "-c1-3", "T4A.TXT", 0 }, 0, 0,
	  "alp\nbra\ncha\ndel\n" },
	{ "sort-past-1000-lines", "/APPS/SORT", { "sort", "-u", "T4SORT.TXT", 0 }, 0, 0,
	  "a\nbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\nz\n" },
	{ "sort-numeric", "/APPS/SORT", { "sort", "-n", "T4NUM.TXT", 0 }, 0, 0,
	  "9\n10\n100\n" },
	{ "tac-past-64k", "/APPS/TAC", { "tac", "T4BIG.TXT", 0 }, 0, 48,
	  "20000\n19999\n19998\n19997\n19996\n19995\n19994\n19993\n" },
	{ "tac-small", "/APPS/TAC", { "tac", "T4A.TXT", 0 }, 0, 0,
	  "delta\ncharlie\nbravo\nalpha\n" },
	{ "date-fixed-iso", "/APPS/DATE", { "date", "-u", "-d", "@1700000000", "+%Y-%m-%dT%H:%M:%S", 0 }, 0, 0,
	  "2023-11-14T22:13:20\n" },
	{ "date-fixed-rfc", "/APPS/DATE", { "date", "-u", "-R", "-d", "@1700000000", 0 }, 0, 0,
	  "Tue, 14 Nov 2023 22:13:20 +0000\n" },
	{ "date-epoch-roundtrip", "/APPS/DATE", { "date", "-u", "-d", "@1700000000", "+%s", 0 }, 0, 0,
	  "1700000000\n" },
};

// Refusals: the SHIPPED binary must exit non-zero AND print nothing on
// stdout. The message text is deliberately not compared.
struct vmref { const char *name; const char *path; char *argv[8]; };
static const struct vmref VMREFUSE[] = {
	{ "tail-follow", "/APPS/TAIL", { "tail", "-f", "T4A.TXT", 0 } },
	{ "cut-no-list", "/APPS/CUT", { "cut", "T4T.TSV", 0 } },
	{ "cut-bad-list", "/APPS/CUT", { "cut", "-f1..3", "T4T.TSV", 0 } },
	{ "sort-key", "/APPS/SORT", { "sort", "-k2", "T4A.TXT", 0 } },
	{ "wc-chars", "/APPS/WC", { "wc", "-m", "T4A.TXT", 0 } },
	{ "date-string", "/APPS/DATE", { "date", "-d", "yesterday", "+%F", 0 } },
	{ "head-bad-number", "/APPS/HEAD", { "head", "-n", "x", "T4A.TXT", 0 } },
	{ "rm-interactive", "/APPS/RM", { "rm", "-i", "T4A.TXT", 0 } },
	{ "mkdir-mode", "/APPS/MKDIR", { "mkdir", "-m", "700", "T4D", 0 } },
};
