/* x86_32_miss.h - GENERATED by tools/x86-32-oracle/gen-miss.py. Do not edit.
 *
 * Instructions the 32-bit core does NOT implement. The expected LENGTH of
 * each one is the assembler's own layout (the distance between two labels),
 * so a MISS that reports the wrong length is caught rather than believed.
 */
#ifndef X86_32_MISS_H
#define X86_32_MISS_H

#include "../types.h"

#define X86_32_MISS_BASE     0x00020000U
#define X86_32_MISS_CODE_LEN 17U

typedef struct { uint32_t addr; uint32_t len; const char *text; } x86_32_miss_case_t;

static const x86_32_miss_case_t g_x86_32_miss_cases[] = {
    { 0x00020000U, 2U, "wbinvd" },
    { 0x00020002U, 3U, "mov" },
    { 0x00020005U, 2U, "arpl" },
    { 0x00020007U, 3U, "bound" },
    { 0x0002000AU, 3U, "lgdtl" },
    { 0x0002000DU, 2U, "invd" },
};
#define X86_32_MISS_CASE_COUNT (sizeof(g_x86_32_miss_cases)/sizeof(g_x86_32_miss_cases[0]))

static const uint8_t g_x86_32_miss_code[17] = {
    0x0F, 0x09, 0x0F, 0x20, 0xC0, 0x63, 0x03, 0x62, 0x45, 0x08, 0x0F, 0x01, 0x10, 0x0F, 0x08, 0x90,
    0x90,
};

#endif /* X86_32_MISS_H */
